-- M124: Seed WC2026 official top-scorer candidates from FIFA published squads + api-football enrichment
--
-- Source: data/wc2026_squads.json — 42/48 teams' official squads pasted from FIFA web (2026-05-31),
-- enriched via api-football /players/squads + /players?team&season=2026 + /players/profiles?search.
-- Match rate: 1070/1140 (93.9%). Remaining 70 deferred to June 4-6 re-pull after FIFA's June-1 deadline
-- when api-football's /players/squads endpoint refreshes with the official final 26-man rosters.
--
-- Strategy:
--   1. Mark ALL existing top_scorer_candidates rows is_active=false (old 1969-row seed is now stale)
--   2. UPSERT 1070 matched players: insert new, update name/team/position on existing, set is_active=true
--   3. After step 2: only WC2026-registered players (with verified api_player_id) are active
--   4. Remaining 70 unmatched players added in M126/M127 after June 4-6 + June 7-10 re-pulls

BEGIN;

-- 1. Mark existing as inactive
UPDATE public.top_scorer_candidates SET is_active = false;

-- Chunk 1/4: 300 rows
INSERT INTO public.top_scorer_candidates (api_player_id, name, team_name, position)
VALUES
  (34374,'Song Bumkeun','South Korea','Goalkeeper'),
  (2890,'Jo Hyeonwoo','South Korea','Goalkeeper'),
  (2892,'Kim Seung-gyu','South Korea','Goalkeeper'),
  (280358,'Jens Castrop','South Korea','Defender'),
  (237218,'Lee Hanbeom','South Korea','Defender'),
  (99211,'Park Jinseob','South Korea','Defender'),
  (2897,'Kim Minjae','South Korea','Defender'),
  (2912,'Kim Moonhwan','South Korea','Defender'),
  (34418,'Kim Taehyeon','South Korea','Defender'),
  (237220,'Lee Taeseok','South Korea','Defender'),
  (197985,'Seol Youngwoo','South Korea','Defender'),
  (34239,'Cho Yumin','South Korea','Defender'),
  (34431,'Lee Donggyeong','South Korea','Midfielder'),
  (24888,'Hwang Heechan','South Korea','Midfielder'),
  (304958,'Yang Hyunjun','South Korea','Midfielder'),
  (2901,'Hwang Inbeom','South Korea','Midfielder'),
  (2906,'Lee Jaesung','South Korea','Midfielder'),
  (34168,'Kim Jingyu','South Korea','Midfielder'),
  (237050,'Eom Jisung','South Korea','Midfielder'),
  (357286,'Bae Junho','South Korea','Midfielder'),
  (927,'Lee Kangin','South Korea','Midfielder'),
  (2909,'Paik Seungho','South Korea','Midfielder'),
  (34211,'Cho Guesung','South Korea','Attacker'),
  (186,'Son Heungmin','South Korea','Attacker'),
  (34710,'Oh Hyeongyu','South Korea','Attacker'),
  (269349,'Lukas Hornicek','Czech Republic','Goalkeeper'),
  (138804,'Matej Kovar','Czech Republic','Goalkeeper'),
  (1231,'Vladimir Coufal','Czech Republic','Defender'),
  (66214,'David Doudera','Czech Republic','Defender'),
  (2252,'Tomas Holes','Czech Republic','Defender'),
  (162964,'Robin Hranac','Czech Republic','Defender'),
  (337740,'Stepan Chaloupek','Czech Republic','Defender'),
  (128793,'David Jurasek','Czech Republic','Defender'),
  (66407,'Ladislav Krejci','Czech Republic','Defender'),
  (1237,'Jaroslav Zeleny','Czech Republic','Defender'),
  (128772,'David Zima','Czech Republic','Defender'),
  (66249,'Pavel Bucha','Czech Republic','Midfielder'),
  (162194,'Lukas Cerv','Czech Republic','Midfielder'),
  (25348,'Vladimir Darida','Czech Republic','Midfielder'),
  (66253,'Tomas Ladra','Czech Republic','Midfielder'),
  (66353,'Lukas Provod','Czech Republic','Midfielder'),
  (241,'Michal Sadilek','Czech Republic','Midfielder'),
  (494332,'Hugo Sochurek','Czech Republic','Midfielder'),
  (386837,'Alexandr Sojka','Czech Republic','Midfielder'),
  (1243,'Tomas Soucek','Czech Republic','Midfielder'),
  (66387,'Pavel Sulc','Czech Republic','Midfielder'),
  (290212,'Denis Visinsky','Czech Republic','Midfielder'),
  (66019,'Adam Hlozek','Czech Republic','Attacker'),
  (818,'Tomas Chory','Czech Republic','Attacker'),
  (66275,'Mojmir Chytil','Czech Republic','Attacker'),
  (271869,'Christophe Kabongo','Czech Republic','Attacker'),
  (66340,'Jan Kuchta','Czech Republic','Attacker'),
  (794,'Patrik Schick','Czech Republic','Attacker'),
  (3275,'Ronwen Williams','South Africa','Goalkeeper'),
  (46245,'Ricardo Goss','South Africa','Goalkeeper'),
  (46417,'Sipho Chaine','South Africa','Goalkeeper'),
  (46601,'Khuliso Mudau','South Africa','Defender'),
  (392387,'Olwethu Makhanya','South Africa','Defender'),
  (163041,'Bradley Cross','South Africa','Defender'),
  (46334,'Aubrey Modiba','South Africa','Defender'),
  (330174,'Thabang Matuludi','South Africa','Defender'),
  (46458,'Nkosinathi Sibisi','South Africa','Defender'),
  (406752,'Ime Okon','South Africa','Defender'),
  (430078,'Samukele Kabini','South Africa','Defender'),
  (510799,'Mbekezeli Mbokazi','South Africa','Defender'),
  (359561,'Kamogelo Sebelebele','South Africa','Defender'),
  (3287,'Teboho Mokoena','South Africa','Midfielder'),
  (268710,'Jayden Adams','South Africa','Midfielder'),
  (194430,'Thalente Mbatha','South Africa','Midfielder'),
  (158433,'Sphephelo Sithole','South Africa','Midfielder'),
  (179893,'Oswin Appollis','South Africa','Attacker'),
  (295977,'Tshepang Moremi','South Africa','Attacker'),
  (201354,'Evidence Makgopa','South Africa','Attacker'),
  (98936,'Lyle Foster','South Africa','Attacker'),
  (127429,'Iqraam Rayners','South Africa','Attacker'),
  (414149,'Relebohile Mofokeng','South Africa','Attacker'),
  (3289,'Themba Zwane','South Africa','Attacker'),
  (354831,'Thapelo Maseko','South Africa','Attacker'),
  (51274,'Maxime Crepeau','Canada','Goalkeeper'),
  (284554,'Owen Goodman','Canada','Goalkeeper'),
  (51148,'Dayne St. Clair','Canada','Goalkeeper'),
  (51295,'Derek Cornelius','Canada','Defender'),
  (509,'Alphonso Davies','Canada','Defender'),
  (327738,'Luc de Fougerolles','Canada','Defender'),
  (78547,'Alistair Johnston','Canada','Defender'),
  (50816,'Richie Laryea','Canada','Defender'),
  (416901,'Niko Sigur','Canada','Defender'),
  (78494,'Joel Waterman','Canada','Defender'),
  (362145,'Ali Ahmed','Canada','Midfielder'),
  (51016,'Tajon Buchanan','Canada','Midfielder'),
  (50788,'Mathieu Choiniere','Canada','Midfielder'),
  (35570,'Stephen Eustaquio','Canada','Midfielder'),
  (284061,'Marcelo Flores','Canada','Midfielder'),
  (328046,'Ismael Kone','Canada','Midfielder'),
  (44798,'Liam Millar','Canada','Midfielder'),
  (50817,'Jonathan Osorio','Canada','Midfielder'),
  (294824,'Nathan-Dylan Saliba','Canada','Midfielder'),
  (50826,'Jacob Shaffelburg','Canada','Midfielder'),
  (8489,'Jonathan David','Canada','Attacker'),
  (313353,'Promise David','Canada','Attacker'),
  (2001,'Cyle Larin','Canada','Attacker'),
  (351587,'Tani Oluwaseyi','Canada','Attacker'),
  (70480,'Osman Hadzikic','Bosnia-Herzegovina','Goalkeeper'),
  (9026,'Nikola Vasilj','Bosnia-Herzegovina','Goalkeeper'),
  (108370,'Martin Zlomislic','Bosnia-Herzegovina','Goalkeeper'),
  (7318,'Amar Dedic','Bosnia-Herzegovina','Defender'),
  (53517,'Dennis Hadzikadunic','Bosnia-Herzegovina','Defender'),
  (1741,'Nikola Katic','Bosnia-Herzegovina','Defender'),
  (1442,'Sead Kolasinac','Bosnia-Herzegovina','Defender'),
  (271350,'Tarik Muharemovic','Bosnia-Herzegovina','Defender'),
  (76867,'Nihad Mujakic','Bosnia-Herzegovina','Defender'),
  (14301,'Stjepan Radeljic','Bosnia-Herzegovina','Defender'),
  (395559,'Kerim Alajbegovic','Bosnia-Herzegovina','Midfielder'),
  (329409,'Esmir Bajraktarevic','Bosnia-Herzegovina','Midfielder'),
  (162222,'Ivan Basic','Bosnia-Herzegovina','Midfielder'),
  (25129,'Dzenis Burnic','Bosnia-Herzegovina','Midfielder'),
  (70514,'Armina Gigovic','Bosnia-Herzegovina','Midfielder'),
  (50006,'Amir Hadziahmetovic','Bosnia-Herzegovina','Midfielder'),
  (340173,'Ermin Mahmic','Bosnia-Herzegovina','Midfielder'),
  (322101,'Amar Memic','Bosnia-Herzegovina','Midfielder'),
  (1324,'Ivan Sunjic','Bosnia-Herzegovina','Midfielder'),
  (264094,'Benjamin Tahirovic','Bosnia-Herzegovina','Midfielder'),
  (314377,'Samed Bazdar','Bosnia-Herzegovina','Attacker'),
  (46930,'Ermedin Demirovic','Bosnia-Herzegovina','Attacker'),
  (790,'Edin Dzeko','Bosnia-Herzegovina','Attacker'),
  (77037,'Jovo Lukic','Bosnia-Herzegovina','Attacker'),
  (28382,'Haris Tabakovic','Bosnia-Herzegovina','Attacker'),
  (42207,'Mahmoud Abunada','Qatar','Goalkeeper'),
  (42055,'Shehab Al Lithi','Qatar','Goalkeeper'),
  (42021,'Meshaal Barsham','Qatar','Goalkeeper'),
  (136503,'Salah Zakaria','Qatar','Goalkeeper'),
  (534032,'Ryan Al Ali','Qatar','Defender'),
  (42063,'Al Hashemi Al Hussein','Qatar','Defender'),
  (2536,'Bassam Al Rawi','Qatar','Defender'),
  (42060,'Sultan Al Brake','Qatar','Defender'),
  (2532,'Boualem Khoukhi','Qatar','Defender'),
  (42288,'Lucas Mendes','Qatar','Defender'),
  (2530,'Pedro Miguel','Qatar','Defender'),
  (2541,'Tarek Salman','Qatar','Defender'),
  (2537,'Karim Boudiaf','Qatar','Midfielder'),
  (2539,'Ahmed Fathi','Qatar','Midfielder'),
  (200981,'Jassem Gaber','Qatar','Midfielder'),
  (2533,'Abdulaziz Hatem','Qatar','Midfielder'),
  (2535,'Assim Madibo','Qatar','Midfielder'),
  (2540,'Tahsin Mohammed','Qatar','Midfielder'),
  (42180,'Mohammed Waad','Qatar','Midfielder'),
  (42421,'Youssef Abdelrisaq','Qatar','Attacker'),
  (2544,'Akram Afif','Qatar','Attacker'),
  (2542,'Ahmed Alaaeldin','Qatar','Attacker'),
  (2545,'Hassan Al Haydos','Qatar','Attacker'),
  (42075,'Edmilson Junior','Qatar','Attacker'),
  (42089,'Mohammed Muntari','Qatar','Attacker'),
  (199297,'Mubarak Shannan','Qatar','Attacker'),
  (42166,'Sebastian Soria','Qatar','Attacker'),
  (25282,'Gregor Kobel','Switzerland','Goalkeeper'),
  (123468,'Marvin Keller','Switzerland','Goalkeeper'),
  (1142,'Yvon Mvogo','Switzerland','Goalkeeper'),
  (5,'Manuel Akanji','Switzerland','Defender'),
  (162414,'Aurele Amenda','Switzerland','Defender'),
  (48372,'Eray Comert','Switzerland','Defender'),
  (2803,'Nico Elvedi','Switzerland','Defender'),
  (349344,'Luca Jaquez','Switzerland','Defender'),
  (48489,'Miro Muheim','Switzerland','Defender'),
  (1631,'Ricardo Rodriguez','Switzerland','Defender'),
  (48378,'Silvan Widmer','Switzerland','Defender'),
  (951,'Michel Aebischer','Switzerland','Midfielder'),
  (952,'Christian Fassnacht','Switzerland','Midfielder'),
  (2807,'Remo Freuler','Switzerland','Midfielder'),
  (48497,'Cedric Itten','Switzerland','Midfielder'),
  (264705,'Ardon Jashari','Switzerland','Midfielder'),
  (163032,'Fabian Rieder','Switzerland','Midfielder'),
  (957,'Djibril Sow','Switzerland','Midfielder'),
  (1464,'Granit Xhaka','Switzerland','Midfielder'),
  (2810,'Denis Zakaria','Switzerland','Midfielder'),
  (123469,'Zeki Amdouni','Switzerland','Attacker'),
  (421,'Breel Embolo','Switzerland','Attacker'),
  (406244,'Johan Manzambi','Switzerland','Attacker'),
  (48648,'Dan Ndoye','Switzerland','Attacker'),
  (48389,'Noah Okafor','Switzerland','Attacker'),
  (48471,'Ruben Vargas','Switzerland','Attacker'),
  (280,'Alisson','Brazil','Goalkeeper'),
  (617,'Ederson','Brazil','Goalkeeper'),
  (2410,'Weverton','Brazil','Goalkeeper'),
  (860,'Alex Sandro','Brazil','Defender'),
  (30497,'Bremer','Brazil','Defender'),
  (618,'Danilo','Brazil','Defender'),
  (24866,'Douglas Santos','Brazil','Defender'),
  (22224,'Gabriel Magalhães','Brazil','Defender'),
  (30424,'Ibanez','Brazil','Defender'),
  (10124,'Leo Pereira','Brazil','Defender'),
  (257,'Marquinhos','Brazil','Defender'),
  (349001,'Wesley','Brazil','Defender'),
  (10135,'Bruno Guimaraes','Brazil','Midfielder'),
  (747,'Casemiro','Brazil','Midfielder'),
  (299,'Fabinho','Brazil','Midfielder'),
  (1646,'Lucas Paqueta','Brazil','Midfielder'),
  (377122,'Endrick','Brazil','Attacker'),
  (127769,'Gabriel Martinelli','Brazil','Attacker'),
  (196156,'Igor Thiago','Brazil','Attacker'),
  (265785,'Luiz Henrique','Brazil','Attacker'),
  (1165,'Matheus Cunha','Brazil','Attacker'),
  (276,'Neymar Junior','Brazil','Attacker'),
  (1496,'Raphinha','Brazil','Attacker'),
  (407806,'Rayan','Brazil','Attacker'),
  (762,'Vinicius Junior','Brazil','Attacker'),
  (2701,'Yassine Bounou','Morocco','Goalkeeper'),
  (545,'Noussair Mazraoui','Morocco','Defender'),
  (162451,'Anass Salah-Eddine','Morocco','Defender'),
  (146772,'Youssef Belammari','Morocco','Defender'),
  (9,'Achraf Hakimi','Morocco','Defender'),
  (283252,'Zakaria El Ouahdi','Morocco','Defender'),
  (21694,'Nayef Aguerd','Morocco','Defender'),
  (278898,'Chadi Riad','Morocco','Defender'),
  (326183,'Redouane Halhal','Morocco','Defender'),
  (18814,'Issa Diop','Morocco','Defender'),
  (415431,'Samir El Mourabet','Morocco','Midfielder'),
  (438688,'Ayyoub Bouaddi','Morocco','Midfielder'),
  (277003,'Neil El Aynaoui','Morocco','Midfielder'),
  (74,'Sofyan Amrabat','Morocco','Midfielder'),
  (129678,'Azzedine Ounahi','Morocco','Midfielder'),
  (340573,'Bilal El Khannouss','Morocco','Midfielder'),
  (161897,'Ismael Saibari','Morocco','Midfielder'),
  (181421,'Abde Ezzalzouli','Morocco','Attacker'),
  (336659,'Chemsdine Talbi','Morocco','Attacker'),
  (36579,'Soufiane Rahimi','Morocco','Attacker'),
  (2722,'Ayoub El Kaabi','Morocco','Attacker'),
  (744,'Brahim Diaz','Morocco','Attacker'),
  (369544,'Gessime Yassine','Morocco','Attacker'),
  (535046,'Ayoube Amaimouni','Morocco','Attacker'),
  (147254,'Craig Gordon','Scotland','Goalkeeper'),
  (18933,'Angus Gunn','Scotland','Goalkeeper'),
  (44937,'Liam Kelly','Scotland','Goalkeeper'),
  (19066,'Grant Hanley','Scotland','Defender'),
  (1111,'Jack Hendry','Scotland','Defender'),
  (44871,'Aaron Hickey','Scotland','Defender'),
  (19987,'Dom Hyam','Scotland','Defender'),
  (44811,'Scott McKenna','Scotland','Defender'),
  (138417,'Nathan Patterson','Scotland','Defender'),
  (1115,'Anthony Ralston','Scotland','Defender'),
  (289,'Andy Robertson','Scotland','Defender'),
  (44865,'John Souttar','Scotland','Defender'),
  (1117,'Kieran Tierney','Scotland','Defender'),
  (1125,'Ryan Christie','Scotland','Midfielder'),
  (433272,'Findlay Curtis','Scotland','Midfielder'),
  (44814,'Lewis Ferguson','Scotland','Midfielder'),
  (130423,'Billy Gilmour','Scotland','Midfielder'),
  (19191,'John McGinn','Scotland','Midfielder'),
  (19077,'Kenny McLean','Scotland','Midfielder'),
  (903,'Scott McTominay','Scotland','Midfielder'),
  (19524,'Che Adams','Scotland','Attacker'),
  (45307,'Lyndon Dykes','Scotland','Attacker'),
  (8794,'George Hirst','Scotland','Attacker'),
  (45175,'Lawrence Shankland','Scotland','Attacker'),
  (430201,'Ross Stewart','Scotland','Attacker'),
  (123742,'Josue Duverger','Haiti','Goalkeeper'),
  (174768,'Alexandre Pierre','Haiti','Goalkeeper'),
  (87789,'Johny Placide','Haiti','Goalkeeper'),
  (12303,'Ricardo Ade','Haiti','Defender'),
  (20850,'Carlens Arcus','Haiti','Defender'),
  (1411,'Hannes Delcroix','Haiti','Defender'),
  (20655,'Jean-Kevin Duverne','Haiti','Defender'),
  (190747,'Martin Experience','Haiti','Defender'),
  (102505,'Duke Lacroix','Haiti','Defender'),
  (275367,'Wilguens Paugain','Haiti','Defender'),
  (573613,'Keeto Thermoncy','Haiti','Defender'),
  (540857,'Carl Fred Sainte','Haiti','Midfielder'),
  (20665,'Jean-Ricner Bellegarde','Haiti','Midfielder'),
  (20538,'Leverton Pierre','Haiti','Midfielder'),
  (237292,'Danley Jean Jacques','Haiti','Midfielder'),
  (371050,'Woodensky Pierre','Haiti','Midfielder'),
  (194242,'Dominique Simon','Haiti','Midfielder'),
  (174915,'Josue Casimir','Haiti','Attacker'),
  (128766,'Louicius Deedson','Haiti','Attacker'),
  (50958,'Derrick Etienne Jr.','Haiti','Attacker'),
  (48535,'Yassin Fortune','Haiti','Attacker'),
  (84087,'Wilson Isidor','Haiti','Attacker'),
  (21613,'Lenny Joseph','Haiti','Attacker'),
  (45020,'Duckens Nazon','Haiti','Attacker'),
  (8601,'Frantzdy Pierrot','Haiti','Attacker'),
  (162733,'Ruben Providence','Haiti','Attacker'),
  (266606,'Chris Brady','United States','Goalkeeper'),
  (50728,'Matt Freese','United States','Goalkeeper'),
  (50999,'Matt Turner','United States','Goalkeeper'),
  (362400,'Max Arfsten','United States','Defender'),
  (38735,'Sergino Dest','United States','Defender'),
  (355994,'Alex Freeman','United States','Defender'),
  (50735,'Mark McKenzie','United States','Defender'),
  (19023,'Tim Ream','United States','Defender'),
  (126949,'Chris Richards','United States','Defender'),
  (19549,'Antonee Robinson','United States','Defender'),
  (50879,'Miles Robinson','United States','Defender'),
  (50852,'Joe Scally','United States','Defender'),
  (50737,'Auston Trusty','United States','Defender'),
  (201713,'Sebastian Berhalter','United States','Midfielder'),
  (415,'Weston McKennie','United States','Midfielder'),
  (51114,'Cristian Roldan','United States','Midfielder'),
  (50739,'Brenden Aaronson','United States','Midfielder'),
  (17,'Christian Pulisic','United States','Midfielder'),
  (161921,'Gio Reyna','United States','Midfielder'),
  (162037,'Malik Tillman','United States','Midfielder')
ON CONFLICT (api_player_id) DO UPDATE SET
  name = EXCLUDED.name,
  team_name = EXCLUDED.team_name,
  position = EXCLUDED.position,
  is_active = true;

-- Chunk 2/4: 300 rows
INSERT INTO public.top_scorer_candidates (api_player_id, name, team_name, position)
VALUES
  (1138,'Timothy Weah','United States','Midfielder'),
  (51248,'Alejandro Zendejas','United States','Midfielder'),
  (138835,'Folarin Balogun','United States','Attacker'),
  (73868,'Ricardo Pepi','United States','Attacker'),
  (427,'Haji Wright','United States','Attacker'),
  (380507,'Altay Bayindir','Turkey','Goalkeeper'),
  (1971,'Ersin Destanoglu','Turkey','Goalkeeper'),
  (49837,'Mert Gunok','Turkey','Goalkeeper'),
  (50218,'Muhammed Sengezer','Turkey','Goalkeeper'),
  (278159,'Ahmetcan Kaplan','Turkey','Defender'),
  (18776,'Caglar Soyuncu','Turkey','Defender'),
  (1719,'Mert Muldur','Turkey','Defender'),
  (62323,'Mustafa Eskihellac','Turkey','Defender'),
  (26300,'Ozan Kabak','Turkey','Defender'),
  (62490,'Samet Akaydin','Turkey','Defender'),
  (412703,'Yusuf Akcicek','Turkey','Defender'),
  (22222,'Zeki Celik','Turkey','Defender'),
  (24963,'Atakan Karazor','Turkey','Midfielder'),
  (1640,'Hakan Calhanoglu','Turkey','Midfielder'),
  (214463,'Ismail Yuksek','Turkey','Midfielder'),
  (25448,'Kaan Ayhan','Turkey','Midfielder'),
  (37155,'Orkun Kokcu','Turkey','Midfielder'),
  (24807,'Salih Ozcan','Turkey','Midfielder'),
  (161790,'Aral Simsir','Turkey','Attacker'),
  (291964,'Arda Guler','Turkey','Attacker'),
  (339887,'Can Uzun','Turkey','Attacker'),
  (388570,'Deniz Gul','Turkey','Attacker'),
  (49857,'Irfan Can Kahveci','Turkey','Attacker'),
  (142959,'Kerem Akturkoglu','Turkey','Attacker'),
  (454,'Yunus Akgun','Turkey','Attacker'),
  (702,'Oliver Baumann','Germany','Goalkeeper'),
  (497,'Manuel Neuer','Germany','Goalkeeper'),
  (399,'Alexander Nubel','Germany','Goalkeeper'),
  (25368,'Waldemar Anton','Germany','Defender'),
  (280074,'Nathaniel Brown','Germany','Defender'),
  (502,'Joshua Kimmich','Germany','Defender'),
  (25158,'David Raum','Germany','Defender'),
  (2285,'Antonio Rudiger','Germany','Defender'),
  (26243,'Nico Schlotterbeck','Germany','Defender'),
  (972,'Jonathan Tah','Germany','Defender'),
  (163189,'Malick Thiaw','Germany','Defender'),
  (714,'Nadiem Amiri','Germany','Midfielder'),
  (511,'Leon Goretzka','Germany','Midfielder'),
  (494131,'Lennart Karl','Germany','Midfielder'),
  (128533,'Jamie Leweling','Germany','Midfielder'),
  (181812,'Jamal Musiala','Germany','Midfielder'),
  (637,'Felix Nmecha','Germany','Midfielder'),
  (328033,'Aleksandar Pavlovic','Germany','Midfielder'),
  (644,'Leroy Sane','Germany','Midfielder'),
  (137210,'Angelo Stiller','Germany','Midfielder'),
  (203224,'Florian Wirtz','Germany','Midfielder'),
  (301027,'Maximilian Beier','Germany','Attacker'),
  (978,'Kai Havertz','Germany','Attacker'),
  (26475,'Deniz Undav','Germany','Attacker'),
  (158054,'Nick Woltemade','Germany','Attacker'),
  (64190,'Yahia Fofana','Ivory Coast','Goalkeeper'),
  (277046,'Mohamed Kone','Ivory Coast','Goalkeeper'),
  (30393,'Alban Lafont','Ivory Coast','Goalkeeper'),
  (135068,'Emmanuel Agbadou','Ivory Coast','Defender'),
  (20836,'Christopher Operi','Ivory Coast','Defender'),
  (354753,'Ousmane Diomande','Ivory Coast','Defender'),
  (161747,'Guela Doue','Ivory Coast','Defender'),
  (22002,'Ghislain Konan','Ivory Coast','Defender'),
  (48119,'Odilon Kossounou','Ivory Coast','Defender'),
  (30504,'Wilfried Singo','Ivory Coast','Defender'),
  (1807,'Evan Ndicka','Ivory Coast','Defender'),
  (30807,'Seko Fofana','Ivory Coast','Midfielder'),
  (263228,'Parfait Guiagon','Ivory Coast','Midfielder'),
  (474591,'Christ Inao Oulai','Ivory Coast','Midfielder'),
  (1642,'Franck Kessie','Ivory Coast','Midfielder'),
  (22149,'Ibrahim Sangare','Ivory Coast','Midfielder'),
  (3243,'Jean Michael Seri','Ivory Coast','Midfielder'),
  (301771,'Simon Adingra','Ivory Coast','Attacker'),
  (275651,'Ange-Yoan Bonny','Ivory Coast','Attacker'),
  (157997,'Amad Diallo','Ivory Coast','Attacker'),
  (334429,'Oumar Diakite','Ivory Coast','Attacker'),
  (513776,'Yan Diomande','Ivory Coast','Attacker'),
  (137303,'Evann Guessand','Ivory Coast','Attacker'),
  (3246,'Nicolas Pepe','Ivory Coast','Attacker'),
  (387643,'Bazoumana Toure','Ivory Coast','Attacker'),
  (162707,'Elye Wahi','Ivory Coast','Attacker'),
  (36967,'Trevor Doornbusch','Curaçao','Goalkeeper'),
  (221,'Eloy Room','Curaçao','Goalkeeper'),
  (37175,'Riechedly Bazoer','Curaçao','Defender'),
  (706,'Joshua Brenet','Curaçao','Defender'),
  (37066,'Roshon van Eijma','Curaçao','Defender'),
  (36970,'Sherel Floranus','Curaçao','Defender'),
  (353808,'Deveron Fonville','Curaçao','Defender'),
  (36857,'Jurien Gaari','Curaçao','Defender'),
  (228,'Armando Obispo','Curaçao','Defender'),
  (194645,'Shurandy Sambo','Curaçao','Defender'),
  (19047,'Juninho Bacuna','Curaçao','Midfielder'),
  (18997,'Leandro Bacuna','Curaçao','Midfielder'),
  (309763,'Livano Comenencia','Curaçao','Midfielder'),
  (37461,'Kevin Felida','Curaçao','Midfielder'),
  (162199,'Ar''jany Martha','Curaçao','Midfielder'),
  (406846,'Tyrese Noslin','Curaçao','Midfielder'),
  (36842,'Godfried Roemeratoe','Curaçao','Midfielder'),
  (163220,'Jeremy Antonisse','Curaçao','Attacker'),
  (906,'Tahith Chong','Curaçao','Attacker'),
  (41627,'Kenji Gorre','Curaçao','Attacker'),
  (161884,'Sontje Hansen','Curaçao','Attacker'),
  (38708,'Gervane Kastaneer','Curaçao','Attacker'),
  (37272,'Brandley Kuwas','Curaçao','Attacker'),
  (18981,'Jurgen Locadia','Curaçao','Attacker'),
  (195067,'Jearl Margaritha','Curaçao','Attacker'),
  (26232,'Mark Flekken','Netherlands','Goalkeeper'),
  (194536,'Robin Roefs','Netherlands','Goalkeeper'),
  (129058,'Bart Verbruggen','Netherlands','Goalkeeper'),
  (18861,'Nathan Ake','Netherlands','Defender'),
  (226,'Denzel Dumfries','Netherlands','Defender'),
  (341642,'Jorrel Hato','Netherlands','Defender'),
  (38747,'Jurrien Timber','Netherlands','Defender'),
  (38695,'Jan Paul van Hecke','Netherlands','Defender'),
  (290,'Virgil van Dijk','Netherlands','Defender'),
  (152849,'Micky van de Ven','Netherlands','Defender'),
  (37524,'Frenkie de Jong','Netherlands','Midfielder'),
  (30432,'Marten de Roon','Netherlands','Midfielder'),
  (542,'Ryan Gravenberch','Netherlands','Midfielder'),
  (36899,'Teun Koopmeiners','Netherlands','Midfielder'),
  (36902,'Tijjani Reijnders','Netherlands','Midfielder'),
  (92993,'Mats Wieffer','Netherlands','Midfielder'),
  (38750,'Brian Brobbey','Netherlands','Attacker'),
  (667,'Memphis Depay','Netherlands','Attacker'),
  (247,'Cody Gakpo','Netherlands','Attacker'),
  (792,'Justin Kluivert','Netherlands','Attacker'),
  (544,'Noa Lang','Netherlands','Attacker'),
  (249,'Donyell Malen','Netherlands','Attacker'),
  (37724,'Crysencio Summerville','Netherlands','Attacker'),
  (25416,'Wout Weghorst','Netherlands','Attacker'),
  (304782,'Tomoki Hayakawa','Japan','Goalkeeper'),
  (33034,'Keisuke Osako','Japan','Goalkeeper'),
  (199578,'Zion Suzuki','Japan','Goalkeeper'),
  (38114,'Ko Itakura','Japan','Defender'),
  (32893,'Hiroki Ito','Japan','Defender'),
  (440,'Yuto Nagatomo','Japan','Defender'),
  (33165,'Ayumu Seko','Japan','Defender'),
  (32887,'Yukinari Sugawara','Japan','Defender'),
  (351014,'Junnosuke Suzuki','Japan','Defender'),
  (32954,'Shogo Taniguchi','Japan','Defender'),
  (2597,'Takehiro Tomiyasu','Japan','Defender'),
  (32858,'Tsuyoshi Watanabe','Japan','Defender'),
  (2598,'Ritsu Doan','Japan','Midfielder'),
  (8500,'Wataru Endo','Japan','Midfielder'),
  (1942,'Junya Ito','Japan','Midfielder'),
  (2601,'Daichi Kamada','Japan','Midfielder'),
  (32862,'Takefusa Kubo','Japan','Midfielder'),
  (33321,'Keito Nakamura','Japan','Midfielder'),
  (33889,'Kaishu Sano','Japan','Midfielder'),
  (33142,'Ao Tanaka','Japan','Midfielder'),
  (375930,'Keisuke Goto','Japan','Attacker'),
  (33224,'Daizen Maeda','Japan','Attacker'),
  (33289,'Koki Ogawa','Japan','Attacker'),
  (422572,'Kento Shiogai','Japan','Attacker'),
  (199143,'Yuito Suzuki','Japan','Attacker'),
  (72155,'Ayase Ueda','Japan','Attacker'),
  (161223,'Viktor Johansson','Sweden','Goalkeeper'),
  (137721,'Gustaf Lagerbielke','Sweden','Goalkeeper'),
  (2851,'Kristoffer Nordfeldt','Sweden','Goalkeeper'),
  (48033,'Jacob Zetterstrom','Sweden','Goalkeeper'),
  (47903,'Hjalmar Ekdal','Sweden','Defender'),
  (47969,'Gabriel Gudmundsson','Sweden','Defender'),
  (137976,'Isak Hien','Sweden','Defender'),
  (889,'Victor Lindelof','Sweden','Defender'),
  (8486,'Eric Smith','Sweden','Defender'),
  (47988,'Carl Starfelt','Sweden','Defender'),
  (198654,'Daniel Svensson','Sweden','Defender'),
  (265820,'Yasin Ayari','Sweden','Midfielder'),
  (347316,'Lucas Bergvall','Sweden','Midfielder'),
  (48047,'Jesper Karlstrom','Sweden','Midfielder'),
  (48002,'Benjamin Nygren','Sweden','Midfielder'),
  (2860,'Ken Sema','Sweden','Midfielder'),
  (226765,'Elliot Stroud','Sweden','Midfielder'),
  (30484,'Mattias Svanberg','Sweden','Midfielder'),
  (350850,'Besfort Zeneli','Sweden','Midfielder'),
  (160925,'Taha Ali','Sweden','Attacker'),
  (47696,'Alexander Bernhardsson','Sweden','Attacker'),
  (153430,'Anthony Elanga','Sweden','Attacker'),
  (18979,'Viktor Gyokeres','Sweden','Attacker'),
  (2864,'Alexander Isak','Sweden','Attacker'),
  (15683,'Gustaf Nilsson','Sweden','Attacker'),
  (533394,'Abdelmouhib Chamakh','Tunisia','Goalkeeper'),
  (49583,'Ali Abdi','Tunisia','Defender'),
  (393977,'Adem Arous','Tunisia','Defender'),
  (2945,'Dylan Bronn','Tunisia','Defender'),
  (533360,'Raed Chikhaoui','Tunisia','Defender'),
  (375608,'Moutaz Neffati','Tunisia','Defender'),
  (163068,'Omar Rekik','Tunisia','Defender'),
  (50030,'Montassar Talbi','Tunisia','Defender'),
  (18942,'Yan Valery','Tunisia','Defender'),
  (49469,'Mortadha Ben Ouanes','Tunisia','Midfielder'),
  (199310,'Anis Ben Slimane','Tunisia','Midfielder'),
  (310196,'Ismael Gharbi','Tunisia','Midfielder'),
  (25300,'Rani Khedira','Tunisia','Midfielder'),
  (67195,'Hadj Mahmoud','Tunisia','Midfielder'),
  (180560,'Hannibal Mejbri','Tunisia','Midfielder'),
  (21587,'Ellyes Skhiri','Tunisia','Midfielder'),
  (42012,'Elias Achouri','Tunisia','Attacker'),
  (533295,'Khalil Ayari','Tunisia','Attacker'),
  (2962,'Firas Chaouat','Tunisia','Attacker'),
  (566059,'Rayan Elloumi','Tunisia','Attacker'),
  (344862,'Hazem Mastouri','Tunisia','Attacker'),
  (323974,'Elias Saad','Tunisia','Attacker'),
  (57518,'Sebastian Tounekti','Tunisia','Attacker'),
  (730,'Thibaut Courtois','Belgium','Goalkeeper'),
  (162511,'Senne Lammens','Belgium','Goalkeeper'),
  (340151,'Mike Penders','Belgium','Goalkeeper'),
  (2920,'Timothy Castagne','Belgium','Defender'),
  (304228,'Zeno Debast','Belgium','Defender'),
  (162007,'Maxim De Cuyper','Belgium','Defender'),
  (162141,'Koni De Winter','Belgium','Defender'),
  (69,'Brandon Mechele','Belgium','Defender'),
  (264,'Thomas Meunier','Belgium','Defender'),
  (312964,'Nathan Ngoy','Belgium','Defender'),
  (375974,'Joaquin Seys','Belgium','Defender'),
  (204043,'Arthur Theate','Belgium','Defender'),
  (629,'Kevin De Bruyne','Belgium','Midfielder'),
  (162714,'Amadou Onana','Belgium','Midfielder'),
  (2120,'Nicolas Raskin','Belgium','Midfielder'),
  (2926,'Youri Tielemans','Belgium','Midfielder'),
  (78,'Hans Vanaken','Belgium','Midfielder'),
  (20,'Axel Witsel','Belgium','Midfielder'),
  (147859,'Charles De Ketelaere','Belgium','Attacker'),
  (1422,'Jeremy Doku','Belgium','Attacker'),
  (340077,'Matias Fernandez-Pardo','Belgium','Attacker'),
  (907,'Romelu Lukaku','Belgium','Attacker'),
  (25458,'Dodi Lukebakio','Belgium','Attacker'),
  (335056,'Diego Moreira','Belgium','Attacker'),
  (1946,'Leandro Trossard','Belgium','Attacker'),
  (2682,'Alireza Beiranvand','Iran','Goalkeeper'),
  (29755,'Seyed Hossein Hosseini','Iran','Goalkeeper'),
  (409495,'Mohammad Khalifeh','Iran','Goalkeeper'),
  (2681,'Payam Niazmand','Iran','Goalkeeper'),
  (136880,'Saleh Hardani','Iran','Defender'),
  (29704,'Shoja Khalilzadeh','Iran','Defender'),
  (2688,'Milad Mohammadi','Iran','Defender'),
  (533035,'Ali Nemati','Iran','Defender'),
  (29775,'Omid Noorafkan','Iran','Defender'),
  (2691,'Ramin Rezaeian','Iran','Defender'),
  (2683,'Rouzbeh Cheshmi','Iran','Midfielder'),
  (19614,'Saeid Ezatolahi','Iran','Midfielder'),
  (29781,'Mehdi Ghaedi','Iran','Midfielder'),
  (2699,'Saman Ghoddos','Iran','Midfielder'),
  (341844,'Mohammad Ghorbani','Iran','Midfielder'),
  (2700,'Alireza Jahanbakhsh','Iran','Midfielder'),
  (134217,'Mohammad Mohebi','Iran','Midfielder'),
  (423753,'Amir Mohammad Razzaghinia','Iran','Midfielder'),
  (2697,'Mehdi Torabi','Iran','Midfielder'),
  (343405,'Aria Yousefi','Iran','Midfielder'),
  (29720,'Ali Alipour','Iran','Attacker'),
  (89912,'Hadi Habibinejad','Iran','Attacker'),
  (29937,'Amirhossein Hosseinzadeh','Iran','Attacker'),
  (613145,'Amirhossein Mahmoudi','Iran','Attacker'),
  (423759,'Kasra Taheri','Iran','Attacker'),
  (42315,'Mehdi Taremi','Iran','Attacker'),
  (18110,'Max Crocombe','New Zealand','Goalkeeper'),
  (94360,'Alex Paulsen','New Zealand','Goalkeeper'),
  (36777,'Michael Woud','New Zealand','Goalkeeper'),
  (430835,'Tyler Bindon','New Zealand','Defender'),
  (51149,'Michael Boxall','New Zealand','Defender'),
  (6931,'Liberato Cacace','New Zealand','Defender'),
  (94405,'Francis de Vries','New Zealand','Defender'),
  (6932,'Callan Elliot','New Zealand','Defender'),
  (94346,'Tim Payne','New Zealand','Defender'),
  (94344,'Nando Pijnaker','New Zealand','Defender'),
  (51307,'Tommy Smith','New Zealand','Defender'),
  (210165,'Finn Surman','New Zealand','Defender'),
  (405957,'Lachlan Bayliss','New Zealand','Midfielder'),
  (94541,'Joe Bell','New Zealand','Midfielder'),
  (180455,'Matt Garbett','New Zealand','Midfielder'),
  (94333,'Eli Just','New Zealand','Midfielder'),
  (94322,'Callum McCowatt','New Zealand','Midfielder'),
  (179856,'Ben Old','New Zealand','Midfielder'),
  (6934,'Alex Rufer','New Zealand','Midfielder'),
  (179862,'Marko Stamenic','New Zealand','Midfielder'),
  (6935,'Sarpreet Singh','New Zealand','Midfielder'),
  (242,'Ryan Thomas','New Zealand','Midfielder'),
  (6865,'Kosta Barbarouses','New Zealand','Attacker'),
  (158688,'Jesse Randall','New Zealand','Attacker'),
  (6938,'Ben Waine','New Zealand','Attacker'),
  (18931,'Chris Wood','New Zealand','Attacker'),
  (550469,'Mohamed Alaa','Egypt','Goalkeeper'),
  (16797,'Mohamed El Shenawy','Egypt','Goalkeeper'),
  (269174,'Mostafa Shobeir','Egypt','Goalkeeper'),
  (16831,'El Mahdy Soliman','Egypt','Goalkeeper'),
  (269621,'Hossam Abdelmagid','Egypt','Defender'),
  (196343,'Mohamed Abdelmonem','Egypt','Defender'),
  (550371,'Tarek Alaa','Egypt','Defender'),
  (2656,'Karim Hafez','Egypt','Defender'),
  (2654,'Mohamed Hany','Egypt','Defender'),
  (16804,'Yasser Ibrahim','Egypt','Defender'),
  (16805,'Rami Rabia','Egypt','Defender'),
  (17269,'Emam Ashour','Egypt','Midfielder'),
  (190575,'Marwan Attia','Egypt','Midfielder'),
  (2660,'Nabil Emad','Egypt','Midfielder'),
  (16862,'Hamdi Fathi','Egypt','Midfielder'),
  (20844,'Haitham Hassan','Egypt','Midfielder'),
  (69196,'Mahmoud Saber','Egypt','Midfielder'),
  (2664,'Mahmoud Hassan "Trezeguet"','Egypt','Midfielder'),
  (395075,'Mostafa Zico','Egypt','Midfielder')
ON CONFLICT (api_player_id) DO UPDATE SET
  name = EXCLUDED.name,
  team_name = EXCLUDED.team_name,
  position = EXCLUDED.position,
  is_active = true;

-- Chunk 3/4: 300 rows
INSERT INTO public.top_scorer_candidates (api_player_id, name, team_name, position)
VALUES
  (16871,'Ahmed Sayed "Zizo"','Egypt','Midfielder'),
  (70535,'Ibrahim Adel','Egypt','Attacker'),
  (81573,'Omar Marmoush','Egypt','Attacker'),
  (306,'Mohamed Salah','Egypt','Attacker'),
  (47270,'Unai Simon','Spain','Goalkeeper'),
  (19465,'David Raya','Spain','Goalkeeper'),
  (182718,'Joan Garcia','Spain','Goalkeeper'),
  (47519,'Pedro Porro','Spain','Defender'),
  (753,'Marcos Llorente','Spain','Defender'),
  (622,'Aymeric Laporte','Spain','Defender'),
  (396623,'Pau Cubarsi','Spain','Defender'),
  (47380,'Marc Pubill','Spain','Defender'),
  (563,'Alejandro Grimaldo','Spain','Defender'),
  (360159,'Rodrigo Hernandez','Spain','Midfielder'),
  (47315,'Martin Zubimendi','Spain','Midfielder'),
  (133609,'Pedri Gonzalez','Spain','Midfielder'),
  (47323,'Mikel Merino','Spain','Midfielder'),
  (1697,'Pablo Paez ''Gavi''','Spain','Midfielder'),
  (182219,'Alex Baena','Spain','Midfielder'),
  (386828,'Lamine Yamal','Spain','Attacker'),
  (931,'Ferran Torres','Spain','Attacker'),
  (47348,'Borja Iglesias','Spain','Attacker'),
  (1323,'Dani Olmo','Spain','Attacker'),
  (338751,'Victor Munoz','Spain','Attacker'),
  (184226,'Yeremy Pino','Spain','Attacker'),
  (44449,'Ahmed Al Kassar','Saudi Arabia','Goalkeeper'),
  (44411,'Mohammed Al Owais','Saudi Arabia','Goalkeeper'),
  (193288,'Nawaf Al Aqidi','Saudi Arabia','Goalkeeper'),
  (44594,'Saud Abdulhamid','Saudi Arabia','Defender'),
  (403087,'Mohammed Abu Al Shamat','Saudi Arabia','Defender'),
  (44701,'Khalid Al Ghannam','Saudi Arabia','Defender'),
  (202381,'Moteb Al Harbi','Saudi Arabia','Defender'),
  (44475,'Abdulelah Al Amri','Saudi Arabia','Defender'),
  (134995,'Nawaf Boushal','Saudi Arabia','Defender'),
  (442343,'Zakaria Hawsawi','Saudi Arabia','Defender'),
  (44335,'Hassan Kadesh','Saudi Arabia','Defender'),
  (44507,'Ali Lajami','Saudi Arabia','Defender'),
  (44367,'Ali Majrashi','Saudi Arabia','Defender'),
  (44362,'Hassan Tambakti','Saudi Arabia','Defender'),
  (304467,'Jehad Thikri','Saudi Arabia','Defender'),
  (44339,'Nasser Al Dawsari','Saudi Arabia','Midfielder'),
  (269172,'Ziyad Al Johani','Saudi Arabia','Midfielder'),
  (306380,'Musab Al Juwayr','Saudi Arabia','Midfielder'),
  (44315,'Abdullah Al Khaibari','Saudi Arabia','Midfielder'),
  (44349,'Mohammed Kanno','Saudi Arabia','Midfielder'),
  (2639,'Sultan Mandash','Saudi Arabia','Midfielder'),
  (147812,'Ayman Yahya','Saudi Arabia','Midfielder'),
  (44324,'Feras Al Brikan','Saudi Arabia','Attacker'),
  (44340,'Salem Al Dawsari','Saudi Arabia','Attacker'),
  (44382,'Abdullah Al Hamdan','Saudi Arabia','Attacker'),
  (44551,'Saleh Al Shehr','Saudi Arabia','Attacker'),
  (15304,'Vozinha','Cape Verde','Goalkeeper'),
  (41764,'Marcio Rosa','Cape Verde','Goalkeeper'),
  (163200,'CJ dos Santos','Cape Verde','Goalkeeper'),
  (41608,'Diney Borges','Cape Verde','Defender'),
  (308689,'Sidny Cabral','Cape Verde','Defender'),
  (21997,'Logan Costa','Cape Verde','Defender'),
  (22139,'Steven Moreira','Cape Verde','Defender'),
  (332056,'Wagner Pina','Cape Verde','Defender'),
  (142016,'Joao Paulo Fernandes','Cape Verde','Defender'),
  (69260,'Roberto ''Pico'' Lopes','Cape Verde','Defender'),
  (268806,'Kelvin Pires','Cape Verde','Defender'),
  (2331,'Ianique ''Stopira'' Tavares','Cape Verde','Defender'),
  (265556,'Telmo Arcanjo','Cape Verde','Midfielder'),
  (37436,'Laros Duarte','Cape Verde','Midfielder'),
  (37435,'Deroy Duarte','Cape Verde','Midfielder'),
  (50745,'Jamiro Monteiro','Cape Verde','Midfielder'),
  (96512,'Kevin Pina','Cape Verde','Midfielder'),
  (128007,'Yannick Semedo','Cape Verde','Midfielder'),
  (309182,'Gilson Benchimol','Cape Verde','Attacker'),
  (1494,'Jovane Cabral','Cape Verde','Attacker'),
  (22265,'Nuno da Costa','Cape Verde','Attacker'),
  (343287,'Dailon Livramento','Cape Verde','Attacker'),
  (50270,'Ryan Mendes','Cape Verde','Attacker'),
  (44612,'Garry Rodrigues','Cape Verde','Attacker'),
  (113580,'Willy Semedo','Cape Verde','Attacker'),
  (291024,'Helio Varela','Cape Verde','Attacker'),
  (22221,'Mike Maignan','France','Goalkeeper'),
  (347211,'Robin Risser','France','Goalkeeper'),
  (21628,'Brice Samba','France','Goalkeeper'),
  (2724,'Lucas Digne','France','Defender'),
  (161907,'Malo Gusto','France','Defender'),
  (33,'Lucas Hernandez','France','Defender'),
  (47300,'Theo Hernandez','France','Defender'),
  (1145,'Ibrahima Konate','France','Defender'),
  (1257,'Jules Kounde','France','Defender'),
  (20995,'Maxence Lacroix','France','Defender'),
  (22090,'William Saliba','France','Defender'),
  (1149,'Dayot Upamecano','France','Defender'),
  (2290,'N''Golo Kante','France','Midfielder'),
  (22147,'Manu Kone','France','Midfielder'),
  (272,'Adrien Rabiot','France','Midfielder'),
  (1271,'Aurelien Tchouameni','France','Midfielder'),
  (336657,'Warren Zaire-Emery','France','Midfielder'),
  (274300,'Maghnes Akliouche','France','Attacker'),
  (161904,'Bradley Barcola','France','Attacker'),
  (156477,'Rayan Cherki','France','Attacker'),
  (153,'Ousmane Dembele','France','Attacker'),
  (343027,'Desire Doue','France','Attacker'),
  (25927,'Jean-Philippe Mateta','France','Attacker'),
  (278,'Kylian Mbappe','France','Attacker'),
  (19617,'Michael Olise','France','Attacker'),
  (21509,'Marcus Thuram','France','Attacker'),
  (119853,'Mory Diaw','Senegal','Goalkeeper'),
  (20566,'Yehvann Diouf','Senegal','Goalkeeper'),
  (2986,'Edouard Mendy','Senegal','Goalkeeper'),
  (371839,'Ilay Camara','Senegal','Defender'),
  (81,'Krepin Diatta','Senegal','Defender'),
  (176541,'El Hadji Malick Diouf','Senegal','Defender'),
  (158121,'Ismail Jakobs','Senegal','Defender'),
  (318,'Kalidou Koulibaly','Senegal','Defender'),
  (408224,'Moustapha Mbow','Senegal','Defender'),
  (313937,'Antoine Mendy','Senegal','Defender'),
  (25916,'Moussa Niakhate','Senegal','Defender'),
  (276184,'Mamadou Sarr','Senegal','Defender'),
  (8450,'Abdoulaye Seck','Senegal','Defender'),
  (374058,'Lamine Camara','Senegal','Midfielder'),
  (41552,'Pathe Ciss','Senegal','Midfielder'),
  (327631,'Habib Diarra','Senegal','Midfielder'),
  (2990,'Idrissa Gana Gueye','Senegal','Midfielder'),
  (20696,'Pape Gueye','Senegal','Midfielder'),
  (237129,'Pape Matar Sarr','Senegal','Midfielder'),
  (14379,'Bara Sapoko Ndiaye','Senegal','Midfielder'),
  (400948,'Assane Diao','Senegal','Attacker'),
  (284072,'Bamba Dieng','Senegal','Attacker'),
  (283058,'Nicolas Jackson','Senegal','Attacker'),
  (304,'Sadio Mane','Senegal','Attacker'),
  (446249,'Ibrahim Mbaye','Senegal','Attacker'),
  (18592,'Iliman Ndiaye','Senegal','Attacker'),
  (2218,'Ismaila Sarr','Senegal','Attacker'),
  (19172,'Orjan Haskjold Nyland','Norway','Goalkeeper'),
  (39082,'Egil Selvik','Norway','Goalkeeper'),
  (264378,'Sander Tangvik','Norway','Goalkeeper'),
  (1119,'Kristoffer Vassbakk Ajer','Norway','Defender'),
  (180937,'Henrik Falchener','Norway','Defender'),
  (265444,'Sondre Langas','Norway','Defender'),
  (39254,'Torbjorn Heggem','Norway','Defender'),
  (39362,'Marcus Holmgren Pedersen','Norway','Defender'),
  (24845,'Julian Ryerson','Norway','Defender'),
  (265782,'David Moller Wolfe','Norway','Defender'),
  (277930,'Thelonious Aasgaard','Norway','Midfielder'),
  (39043,'Fredrik Aursnes','Norway','Midfielder'),
  (39064,'Patrick Berg','Norway','Midfielder'),
  (1934,'Sander Berge','Norway','Midfielder'),
  (278133,'Oscar Bobb','Norway','Midfielder'),
  (39073,'Jens Petter Hauge','Norway','Midfielder'),
  (314511,'Antonio Nusa','Norway','Midfielder'),
  (301528,'Andreas Schjelderup','Norway','Midfielder'),
  (36980,'Morten Thorsby','Norway','Midfielder'),
  (39143,'Kristian Thorstvedt','Norway','Midfielder'),
  (1100,'Erling Haaland','Norway','Attacker'),
  (2032,'Jorgen Strand Larsen','Norway','Attacker'),
  (197933,'Ahmed Basil','Iraq','Goalkeeper'),
  (53886,'Jalal Hassan','Iraq','Goalkeeper'),
  (123802,'Fahad Talib','Iraq','Goalkeeper'),
  (145465,'Hussein Ali','Iraq','Defender'),
  (271444,'Merchas Doski','Iraq','Defender'),
  (453073,'Akam Hashem','Iraq','Defender'),
  (72132,'Maytham Jabbar','Iraq','Defender'),
  (340221,'Dario Naamo','Iraq','Defender'),
  (15769,'Frans Putros','Iraq','Defender'),
  (42261,'Rebin Sulaka','Iraq','Defender'),
  (296373,'Zaid Tahseen','Iraq','Defender'),
  (345750,'Ahmed Yahya','Iraq','Defender'),
  (542866,'Hasan Abdulkareem','Iraq','Midfielder'),
  (47792,'Amir Al Ammari','Iraq','Midfielder'),
  (282065,'Youssef Amyn','Iraq','Midfielder'),
  (140747,'Ibrahim Bayesh','Iraq','Midfielder'),
  (265448,'Marko Farji','Iraq','Midfielder'),
  (100079,'Peter Gwargis','Iraq','Midfielder'),
  (284295,'Zidane Iqbal','Iraq','Midfielder'),
  (72131,'Zaid Ismail','Iraq','Midfielder'),
  (299813,'Ali Jassim','Iraq','Midfielder'),
  (72134,'Karar Nabeel','Iraq','Midfielder'),
  (567870,'Jussef Nasrawe','Iraq','Midfielder'),
  (395628,'Ahmed Qasim','Iraq','Midfielder'),
  (48129,'Aimar Sher','Iraq','Midfielder'),
  (48025,'Kevin Yakob','Iraq','Midfielder'),
  (49451,'Aymen Hussein','Iraq','Attacker'),
  (19599,'Emiliano Martínez','Argentina','Goalkeeper'),
  (47296,'Geronimo Rulli','Argentina','Goalkeeper'),
  (2465,'Juan Musso','Argentina','Goalkeeper'),
  (6503,'Nahuel Molina','Argentina','Defender'),
  (2468,'Gonzalo Montiel','Argentina','Defender'),
  (30776,'Cristian Romero','Argentina','Defender'),
  (6,'Leonardo Balerdi','Argentina','Defender'),
  (624,'Nicolas Otamendi','Argentina','Defender'),
  (6000,'Lisandro Martinez','Argentina','Defender'),
  (529,'Nicolas Tagliafico','Argentina','Defender'),
  (6231,'Facundo Medina','Argentina','Defender'),
  (271,'Leandro Paredes','Argentina','Midfielder'),
  (6716,'Alexis Mac Allister','Argentina','Midfielder'),
  (2472,'Rodrigo De Paul','Argentina','Midfielder'),
  (1578,'Giovani Lo Celso','Argentina','Midfielder'),
  (6002,'Exequiel Palacios','Argentina','Midfielder'),
  (5996,'Enzo Fernandez','Argentina','Midfielder'),
  (319572,'Valentin Barco','Argentina','Midfielder'),
  (154,'Lionel Messi','Argentina','Attacker'),
  (6009,'Julian Alvarez','Argentina','Attacker'),
  (6067,'Thiago Almada','Argentina','Attacker'),
  (350037,'Nicolas Paz','Argentina','Attacker'),
  (26315,'Nicolas Gonzalez','Argentina','Attacker'),
  (323935,'Giuliano Simeone','Argentina','Attacker'),
  (295513,'Jose Manuel Lopez','Argentina','Attacker'),
  (7598,'Patrick Pentz','Austria','Goalkeeper'),
  (7525,'Alexander Schlager','Austria','Goalkeeper'),
  (221605,'Florian Wiegele','Austria','Goalkeeper'),
  (126640,'David Affengruber','Austria','Defender'),
  (505,'David Alaba','Austria','Defender'),
  (25287,'Kevin Danso','Austria','Defender'),
  (25314,'Marco Friedl','Austria','Defender'),
  (26240,'Philipp Lienhart','Austria','Defender'),
  (25915,'Phillipp Mwene','Austria','Defender'),
  (711,'Stefan Posch','Austria','Defender'),
  (7327,'Alexander Prass','Austria','Defender'),
  (7090,'Michael Svoboda','Austria','Defender'),
  (715,'Christoph Baumgartner','Austria','Midfielder'),
  (138935,'Carney Chukwuemeka','Austria','Midfielder'),
  (719,'Florian Grillitsch','Austria','Midfielder'),
  (1157,'Konrad Laimer','Austria','Midfielder'),
  (1159,'Marcel Sabitzer','Austria','Midfielder'),
  (1095,'Xaver Schlager','Austria','Midfielder'),
  (7562,'Romano Schmid','Austria','Midfielder'),
  (417,'Alessandro Schopf','Austria','Midfielder'),
  (7328,'Nicolas Seiwald','Austria','Midfielder'),
  (327895,'Paul Wanner','Austria','Midfielder'),
  (126642,'Patrick Wimmer','Austria','Midfielder'),
  (18830,'Marko Arnautovic','Austria','Attacker'),
  (25297,'Michael Gregoritsch','Austria','Attacker'),
  (7722,'Sasa Kalajdzic','Austria','Attacker'),
  (140607,'Yazid Abulaila','Jordan','Goalkeeper'),
  (163884,'Abdallah Al Fakhouri','Jordan','Goalkeeper'),
  (213985,'Ahmad Al Juaidi','Jordan','Goalkeeper'),
  (102538,'Mohammad Abualnadi','Jordan','Defender'),
  (140608,'Yousef Abu Al Jazar','Jordan','Defender'),
  (542822,'Husam Abu Dahab','Jordan','Defender'),
  (310785,'Mohannad Abu Taha','Jordan','Defender'),
  (53900,'Yazan Al Arab','Jordan','Defender'),
  (213978,'Saed Al Rosan','Jordan','Defender'),
  (542855,'Ahmad Assaf','Jordan','Defender'),
  (53902,'Ehsan Haddad','Jordan','Defender'),
  (72140,'Saleem Obaid','Jordan','Defender'),
  (213980,'Nizar Al Rashdan','Jordan','Midfielder'),
  (140609,'Noor Al Rawabdeh','Jordan','Midfielder'),
  (104242,'Rajaei Ayed','Jordan','Midfielder'),
  (198211,'Amer Jamous','Jordan','Midfielder'),
  (618026,'Yousef Qashi','Jordan','Midfielder'),
  (542768,'Ibrahim Sadeh','Jordan','Midfielder'),
  (393152,'Mohammad Abu Zraiq','Jordan','Attacker'),
  (15286,'Mousa Al Tamari','Jordan','Attacker'),
  (575283,'Ali Azaizeh','Jordan','Attacker'),
  (164026,'Ali Olwan','Jordan','Attacker'),
  (432841,'Ibrahim Sabra','Jordan','Attacker'),
  (190485,'Diogo Costa','Portugal','Goalkeeper'),
  (1590,'Jose Sa','Portugal','Goalkeeper'),
  (46672,'Rui Silva','Portugal','Goalkeeper'),
  (41960,'Ricardo Velho','Portugal','Goalkeeper'),
  (161939,'Tomas Araujo','Portugal','Defender'),
  (855,'Joao Cancelo','Portugal','Defender'),
  (886,'Diogo Dalot','Portugal','Defender'),
  (2676,'Ruben Dias','Portugal','Defender'),
  (265595,'Goncalo Inacio','Portugal','Defender'),
  (263482,'Nuno Mendes','Portugal','Defender'),
  (41621,'Matheus Nunes','Portugal','Defender'),
  (96364,'Nelson Semedo','Portugal','Defender'),
  (336671,'Renato Veiga','Portugal','Defender'),
  (1485,'Bruno Fernandes','Portugal','Midfielder'),
  (335051,'Joao Neves','Portugal','Midfielder'),
  (119612,'Bernardo Silva','Portugal','Midfielder'),
  (128384,'Vitinha','Portugal','Midfielder'),
  (161585,'Francisco Conceicao','Portugal','Attacker'),
  (583,'Joao Felix','Portugal','Attacker'),
  (925,'Goncalo Guedes','Portugal','Attacker'),
  (22236,'Rafael Leao','Portugal','Attacker'),
  (1864,'Pedro Neto','Portugal','Attacker'),
  (41585,'Goncalo Ramos','Portugal','Attacker'),
  (874,'Cristiano Ronaldo','Portugal','Attacker'),
  (41112,'Francisco Trincao','Portugal','Attacker'),
  (2481,'Alvaro Montero','Colombia','Goalkeeper'),
  (2482,'Camilo Vargas','Colombia','Goalkeeper'),
  (313,'David Ospina','Colombia','Goalkeeper'),
  (13736,'Daniel Munoz','Colombia','Defender'),
  (30,'Santiago Arias','Colombia','Defender'),
  (168,'Davinson Sanchez','Colombia','Defender'),
  (1929,'Jhon Lucumi','Colombia','Defender'),
  (2484,'Yerry Mina','Colombia','Defender'),
  (13571,'Willer Ditta','Colombia','Defender'),
  (2483,'Deiver Machado','Colombia','Defender'),
  (64268,'Johan Mojica','Colombia','Defender'),
  (324034,'Gustavo Puerta','Colombia','Midfielder'),
  (517,'James Rodriguez','Colombia','Midfielder'),
  (2490,'Jefferson Lerma','Colombia','Midfielder'),
  (13708,'Jhon Arias','Colombia','Midfielder'),
  (5994,'Jorge Carrascal','Colombia','Midfielder'),
  (6005,'Juan Fernando Quintero','Colombia','Midfielder'),
  (195104,'Richard Rios','Colombia','Midfielder'),
  (289592,'Kevin Castano','Colombia','Midfielder'),
  (13376,'Jaminton Campaz','Colombia','Midfielder'),
  (13151,'Juan Portilla','Colombia','Midfielder'),
  (2489,'Luis Diaz','Colombia','Attacker')
ON CONFLICT (api_player_id) DO UPDATE SET
  name = EXCLUDED.name,
  team_name = EXCLUDED.team_name,
  position = EXCLUDED.position,
  is_active = true;

-- Chunk 4/4: 151 rows
INSERT INTO public.top_scorer_candidates (api_player_id, name, team_name, position)
VALUES
  (47237,'Luis Suarez','Colombia','Attacker'),
  (24810,'Jhon Cordoba','Colombia','Attacker'),
  (345748,'Carlos Gomez','Colombia','Attacker'),
  (47582,'Juan Camilo Hernandez','Colombia','Attacker'),
  (24012,'Lionel Mpasi','DR Congo','Goalkeeper'),
  (48501,'Thimothy Fayulu','DR Congo','Goalkeeper'),
  (314509,'Matthieu Epolo','DR Congo','Goalkeeper'),
  (375,'Chancel Mbemba','DR Congo','Defender'),
  (18846,'Aaron Wan-Bissaka','DR Congo','Defender'),
  (19182,'Alex Tuanzebe','DR Congo','Defender'),
  (18816,'Arthur Masuaku','DR Congo','Defender'),
  (21098,'Joris Kayembe','DR Congo','Defender'),
  (199767,'Steve Kapuadi','DR Congo','Defender'),
  (44791,'Aaron Tshibola','DR Congo','Defender'),
  (8445,'Dylan Batubinsika','DR Congo','Defender'),
  (24245,'Gédéon Kalulu','DR Congo','Defender'),
  (365331,'Noah Sadiki','DR Congo','Midfielder'),
  (21101,'Samuel Moutoussamy','DR Congo','Midfielder'),
  (1424,'Edo Kayembe','DR Congo','Midfielder'),
  (375598,'Ngal''ayel Mukau','DR Congo','Midfielder'),
  (48555,'Charles Pickel','DR Congo','Midfielder'),
  (129670,'Nathanael Mbuku','DR Congo','Midfielder'),
  (279482,'Brian Cipenga','DR Congo','Midfielder'),
  (3034,'Meschack Elia','DR Congo','Midfielder'),
  (47545,'Gael Kakuta','DR Congo','Midfielder'),
  (8627,'Theo Bongonda','DR Congo','Attacker'),
  (179699,'Fiston Mayele','DR Congo','Attacker'),
  (3033,'Cedric Bakambu','DR Congo','Attacker'),
  (20674,'Simon Banza','DR Congo','Attacker'),
  (20649,'Yoane Wissa','DR Congo','Attacker'),
  (72120,'Botirali Ergashev','Uzbekistan','Goalkeeper'),
  (73534,'Utkir Yusupov','Uzbekistan','Goalkeeper'),
  (72122,'Khojiakbar Alijonov','Uzbekistan','Defender'),
  (34121,'Rustamjon Ashurmatov','Uzbekistan','Defender'),
  (416964,'Bekhruz Karimov','Uzbekistan','Defender'),
  (360114,'Abdukodir Khusanov','Uzbekistan','Defender'),
  (532759,'Farrukh Sayfiev','Uzbekistan','Defender'),
  (65571,'Avazbek Ulmasaliev','Uzbekistan','Defender'),
  (358427,'Jakhongir Urozov','Uzbekistan','Defender'),
  (312231,'Ruslanbek Yiyanov','Uzbekistan','Defender'),
  (363723,'Sherzod Esanov','Uzbekistan','Midfielder'),
  (53835,'Odiljon Hamrobekov','Uzbekistan','Midfielder'),
  (65576,'Jamshid Iskanderov','Uzbekistan','Midfielder'),
  (73522,'Akmal Mozgovoy','Uzbekistan','Midfielder'),
  (50272,'Otabek Shukurov','Uzbekistan','Midfielder'),
  (65584,'Azizbek Amonov','Uzbekistan','Attacker'),
  (263676,'Abbosbek Fayzullaev','Uzbekistan','Attacker'),
  (53836,'Jaloliddin Masharipov','Uzbekistan','Attacker'),
  (53535,'Eldor Shomurodov','Uzbekistan','Attacker'),
  (72128,'Igor Sergeev','Uzbekistan','Attacker'),
  (546505,'Sherzod Temirov','Uzbekistan','Attacker'),
  (19088,'Dean Henderson','England','Goalkeeper'),
  (2932,'Jordan Pickford','England','Goalkeeper'),
  (162489,'James Trafford','England','Goalkeeper'),
  (18961,'Dan Burn','England','Defender'),
  (67971,'Marc Guehi','England','Defender'),
  (19545,'Reece James','England','Defender'),
  (19354,'Ezri Konsa','England','Defender'),
  (158694,'Tino Livramento','England','Defender'),
  (158698,'Jarell Quansah','England','Defender'),
  (19235,'Djed Spence','England','Defender'),
  (626,'John Stones','England','Defender'),
  (138908,'Elliott Anderson','England','Midfielder'),
  (129718,'Jude Bellingham','England','Midfielder'),
  (19586,'Eberechi Eze','England','Midfielder'),
  (292,'Jordan Henderson','England','Midfielder'),
  (284322,'Kobbie Mainoo','England','Midfielder'),
  (2937,'Declan Rice','England','Midfielder'),
  (19170,'Morgan Rogers','England','Midfielder'),
  (138787,'Anthony Gordon','England','Attacker'),
  (184,'Harry Kane','England','Attacker'),
  (136723,'Noni Madueke','England','Attacker'),
  (909,'Marcus Rashford','England','Attacker'),
  (1460,'Bukayo Saka','England','Attacker'),
  (19974,'Ivan Toney','England','Attacker'),
  (19366,'Ollie Watkins','England','Attacker'),
  (1305,'Dominik Livakovic','Croatia','Goalkeeper'),
  (524,'Dominik Kotarski','Croatia','Goalkeeper'),
  (14268,'Ivor Pandur','Croatia','Goalkeeper'),
  (129033,'Josko Gvardiol','Croatia','Defender'),
  (1902,'Duje Caleta-Car','Croatia','Defender'),
  (14701,'Josip Sutalo','Croatia','Defender'),
  (125171,'Josip Stanisic','Croatia','Defender'),
  (1084,'Marin Pongracic','Croatia','Defender'),
  (30827,'Martin Erlic','Croatia','Defender'),
  (387521,'Luka Vuskovic','Croatia','Defender'),
  (754,'Luka Modric','Croatia','Midfielder'),
  (2291,'Mateo Kovacic','Croatia','Midfielder'),
  (260865,'Mario Pasalic','Croatia','Midfielder'),
  (842,'Nikola Vlasic','Croatia','Midfielder'),
  (7332,'Luka Sucic','Croatia','Midfielder'),
  (295026,'Martin Baturina','Croatia','Midfielder'),
  (14395,'Kristijan Jakic','Croatia','Midfielder'),
  (348205,'Petar Sucic','Croatia','Midfielder'),
  (1322,'Nikola Moro','Croatia','Midfielder'),
  (284869,'Toni Fruk','Croatia','Midfielder'),
  (207,'Ivan Perisic','Croatia','Attacker'),
  (726,'Andrej Kramaric','Croatia','Attacker'),
  (46746,'Ante Budimir','Croatia','Attacker'),
  (66055,'Petar Musa','Croatia','Attacker'),
  (202696,'Igor Matanovic','Croatia','Attacker'),
  (480108,'Benjamin Asare','Ghana','Goalkeeper'),
  (434273,'Solomon Agbasi','Ghana','Goalkeeper'),
  (144709,'Joseph Anang','Ghana','Goalkeeper'),
  (392258,'Paul Reverson','Ghana','Goalkeeper'),
  (369425,'Jonas Adjetey','Ghana','Defender'),
  (21996,'Abdul Rahman Baba','Ghana','Defender'),
  (21633,'Alexander Djiku','Ghana','Defender'),
  (7578,'Gideon Mensah','Ghana','Defender'),
  (15900,'Abdul Mumin','Ghana','Defender'),
  (137223,'Jerome Opoku','Ghana','Defender'),
  (404172,'Kojo Peprah Oppong','Ghana','Defender'),
  (196187,'Alidu Seidu','Ghana','Defender'),
  (191240,'Marvin Senaya','Ghana','Defender'),
  (337426,'Augustine Boakye','Ghana','Midfielder'),
  (303467,'Abdul Fatawu','Ghana','Midfielder'),
  (21010,'Elisha Owusu','Ghana','Midfielder'),
  (49,'Thomas Partey','Ghana','Midfielder'),
  (3608,'Kwasi Sibo','Ghana','Midfielder'),
  (199837,'Kamaldeen Sulemana','Ghana','Midfielder'),
  (475575,'Caleb Yirenkyi','Ghana','Midfielder'),
  (3428,'Jordan Ayew','Ghana','Attacker'),
  (411800,'Christopher Bonsu Baah','Ghana','Attacker'),
  (410016,'Prince Kwabena Adu','Ghana','Attacker'),
  (350856,'Ernest Nuamah','Ghana','Attacker'),
  (19281,'Antoine Semenyo','Ghana','Attacker'),
  (2968,'Orlando Mosquera','Panama','Goalkeeper'),
  (2967,'Luis Mejia','Panama','Goalkeeper'),
  (57861,'Cesar Samudio','Panama','Goalkeeper'),
  (2975,'Cesar Blackman','Panama','Defender'),
  (57803,'Jorge Gutierrez','Panama','Defender'),
  (2973,'Amir Murillo','Panama','Defender'),
  (2971,'Fidel Escobar','Panama','Defender'),
  (7197,'Andres Andrade','Panama','Defender'),
  (328148,'Edgardo Farina','Panama','Defender'),
  (57739,'Jose Cordoba','Panama','Defender'),
  (2970,'Eric Davis','Panama','Defender'),
  (57667,'Jiovany Ramos','Panama','Defender'),
  (81659,'Roderick Miller','Panama','Defender'),
  (2977,'Anibal Godoy','Panama','Midfielder'),
  (57807,'Adalberto Carrasquilla','Panama','Midfielder'),
  (71230,'Carlos Harvey','Panama','Midfielder'),
  (554208,'Cristian Martinez','Panama','Midfielder'),
  (2979,'Jose Luis Rodriguez','Panama','Midfielder'),
  (57875,'Cesar Yanis','Panama','Midfielder'),
  (46855,'Yoel Barcenas','Panama','Midfielder'),
  (2978,'Alberto Quintero','Panama','Midfielder'),
  (292396,'Azarias Londono','Panama','Midfielder'),
  (96615,'Ismael Diaz','Panama','Attacker'),
  (51648,'Cecilio Waterman','Panama','Attacker'),
  (2983,'Jose Fajardo','Panama','Attacker')
ON CONFLICT (api_player_id) DO UPDATE SET
  name = EXCLUDED.name,
  team_name = EXCLUDED.team_name,
  position = EXCLUDED.position,
  is_active = true;

-- Backfill flag_code from teams table (M124b fix 2026-05-31).
-- Reason: INSERT VALUES rows above do not carry flag_code per-player, so newly inserted players
-- were left with flag_code = NULL (140 of 1051 rows on first apply). teams.flag_code is the source
-- of truth — every team_name in this seed exists in public.teams.
UPDATE public.top_scorer_candidates tsc
SET flag_code = t.flag_code
FROM public.teams t
WHERE tsc.team_name = t.name AND tsc.flag_code IS NULL AND tsc.is_active = true;

COMMIT;

-- Verify
DO $$
DECLARE v_active int; v_total int;
BEGIN
  SELECT COUNT(*) INTO v_active FROM public.top_scorer_candidates WHERE is_active = true;
  SELECT COUNT(*) INTO v_total  FROM public.top_scorer_candidates;
  RAISE NOTICE 'top_scorer_candidates: % active / % total', v_active, v_total;
END $$;
