-- M128 (PROD ONLY): sync top_scorer_candidates to data/wc2026_squads.json (2026-06-02)
--
-- Source of truth: JSON file. Three operations:
--   1. UPDATE rows matched by api_player_id (renames + reactivations + meta refresh)
--   2. INSERT rows with api_player_id not in DB (new players + 47 negative placeholders)
--   3. UPDATE is_active=false for any active DB row NOT in JSON (cuts)
--   4. Backfill flag_code from teams table
--
-- Placeholder ids (-19 to -65) represent players not yet found in api-football
-- (low-coverage leagues + provisional backups). Resolve via post-game lineup sync
-- per docs/PLAN_LINEUP_VERIFICATION.md.

CREATE TEMP TABLE _incoming_squad (
  team_name        text NOT NULL,
  name             text NOT NULL,
  api_player_id    integer NOT NULL,
  position         text,
  id_verification  text
) ON COMMIT DROP;

INSERT INTO _incoming_squad (team_name, name, api_player_id, position, id_verification) VALUES
  ('Mexico', 'Carlos Acevedo', 35769, 'GK', 'fully_verified'),
  ('Mexico', 'Guillermo Ochoa', 2098, 'GK', 'squad_ok_name_suspect'),
  ('Mexico', 'Raúl Rangel', 270774, 'GK', 'squad_ok_name_suspect'),
  ('Mexico', 'Edson Álvarez', 2869, 'DF', 'fully_verified'),
  ('Mexico', 'Mateo Chávez', 390002, 'DF', 'fully_verified'),
  ('Mexico', 'Jesús Gallardo', 2881, 'DF', 'fully_verified'),
  ('Mexico', 'César Montes', 2873, 'DF', 'fully_verified'),
  ('Mexico', 'Israel Reyes', 127227, 'DF', 'fully_verified'),
  ('Mexico', 'Jorge Sánchez', 2878, 'DF', 'fully_verified'),
  ('Mexico', 'Johan Vásquez', 35544, 'DF', 'fully_verified'),
  ('Mexico', 'Luis Chávez', 35690, 'MF', 'squad_missing_name_ok'),
  ('Mexico', 'Álvaro Fidalgo', 750, 'MF', 'fully_verified'),
  ('Mexico', 'Brian Gutiérrez', 212233, 'MF', 'fully_verified'),
  ('Mexico', 'Erik Lira', 266345, 'MF', 'fully_verified'),
  ('Mexico', 'Gilberto Mora', 482605, 'MF', 'fully_verified'),
  ('Mexico', 'Luis Romo', 35970, 'MF', 'fully_verified'),
  ('Mexico', 'Orbelín Pineda', 35576, 'MF', 'fully_verified'),
  ('Mexico', 'Obed Vargas', 313383, 'MF', 'fully_verified'),
  ('Mexico', 'Roberto Alvarado', 2879, 'FW', 'fully_verified'),
  ('Mexico', 'Santiago Giménez', 94562, 'FW', 'squad_missing_name_ok'),
  ('Mexico', 'Armando González', 291713, 'FW', 'fully_verified'),
  ('Mexico', 'César Huerta', 36111, 'FW', 'squad_missing_name_ok'),
  ('Mexico', 'Raúl Jiménez', 2887, 'FW', 'fully_verified'),
  ('Mexico', 'Guillermo Martínez', 36088, 'FW', 'fully_verified'),
  ('Mexico', 'Julián Quiñones', 35532, 'FW', 'fully_verified'),
  ('Mexico', 'Alexis Vega', 2889, 'FW', 'squad_ok_name_suspect'),
  ('South Korea', 'Song Bumkeun', 34374, 'GK', 'fully_verified'),
  ('South Korea', 'Jo Hyeonwoo', 2890, 'GK', 'fully_verified'),
  ('South Korea', 'Kim Seung-gyu', 2892, 'GK', 'fully_verified'),
  ('South Korea', 'Jens Castrop', 280358, 'DF', 'fully_verified'),
  ('South Korea', 'Lee Hanbeom', 237218, 'DF', 'fully_verified'),
  ('South Korea', 'Park Jinseob', 99211, 'DF', 'fully_verified'),
  ('South Korea', 'Lee Kihyuk', -52, 'DF', 'placeholder_lineup_pending'),
  ('South Korea', 'Kim Minjae', 2897, 'DF', 'fully_verified'),
  ('South Korea', 'Kim Moonhwan', 2912, 'DF', 'fully_verified'),
  ('South Korea', 'Kim Taehyeon', 34418, 'DF', 'fully_verified'),
  ('South Korea', 'Lee Taeseok', 237220, 'DF', 'fully_verified'),
  ('South Korea', 'Seol Youngwoo', 197985, 'DF', 'fully_verified'),
  ('South Korea', 'Lee Donggyeong', 34431, 'MF', 'fully_verified'),
  ('South Korea', 'Hwang Heechan', 24888, 'MF', 'fully_verified'),
  ('South Korea', 'Yang Hyunjun', 304958, 'MF', 'fully_verified'),
  ('South Korea', 'Hwang Inbeom', 2901, 'MF', 'fully_verified'),
  ('South Korea', 'Lee Jaesung', 2906, 'MF', 'fully_verified'),
  ('South Korea', 'Kim Jingyu', 34168, 'MF', 'fully_verified'),
  ('South Korea', 'Eom Jisung', 237050, 'MF', 'fully_verified'),
  ('South Korea', 'Bae Junho', 357286, 'MF', 'fully_verified'),
  ('South Korea', 'Lee Kangin', 927, 'MF', 'fully_verified'),
  ('South Korea', 'Paik Seungho', 2909, 'MF', 'fully_verified'),
  ('South Korea', 'Cho Guesung', 34211, 'FW', 'fully_verified'),
  ('South Korea', 'Son Heungmin', 186, 'FW', 'fully_verified'),
  ('South Korea', 'Oh Hyeongyu', 34710, 'FW', 'fully_verified'),
  ('South Korea', 'Cho Wije', -51, 'DF', 'placeholder_lineup_pending'),
  ('Czech Republic', 'Lukas Hornicek', 269349, 'GK', 'fully_verified'),
  ('Czech Republic', 'Matej Kovar', 138804, 'GK', 'fully_verified'),
  ('Czech Republic', 'Jindrich Stanrk', 66347, 'GK', 'club_match'),
  ('Czech Republic', 'Vladimir Coufal', 1231, 'DF', 'fully_verified'),
  ('Czech Republic', 'David Doudera', 66214, 'DF', 'fully_verified'),
  ('Czech Republic', 'Tomas Holes', 2252, 'DF', 'fully_verified'),
  ('Czech Republic', 'Robin Hranac', 162964, 'DF', 'fully_verified'),
  ('Czech Republic', 'Stepan Chaloupek', 337740, 'DF', 'fully_verified'),
  ('Czech Republic', 'David Jurasek', 128793, 'DF', 'fully_verified'),
  ('Czech Republic', 'Ladislav Krejci', 66407, 'DF', 'fully_verified'),
  ('Czech Republic', 'Jaroslav Zeleny', 1237, 'DF', 'fully_verified'),
  ('Czech Republic', 'David Zima', 128772, 'DF', 'fully_verified'),
  ('Czech Republic', 'Lukas Cerv', 162194, 'MF', 'fully_verified'),
  ('Czech Republic', 'Vladimir Darida', 25348, 'MF', 'fully_verified'),
  ('Czech Republic', 'Lukas Provod', 66353, 'MF', 'fully_verified'),
  ('Czech Republic', 'Michal Sadilek', 241, 'MF', 'fully_verified'),
  ('Czech Republic', 'Hugo Sochurek', 494332, 'MF', 'squad_missing_name_ok'),
  ('Czech Republic', 'Alexandr Sojka', 386837, 'MF', 'fully_verified'),
  ('Czech Republic', 'Tomas Soucek', 1243, 'MF', 'fully_verified'),
  ('Czech Republic', 'Pavel Sulc', 66387, 'MF', 'fully_verified'),
  ('Czech Republic', 'Denis Visinsky', 290212, 'MF', 'fully_verified'),
  ('Czech Republic', 'Adam Hlozek', 66019, 'FW', 'fully_verified'),
  ('Czech Republic', 'Tomas Chory', 818, 'FW', 'fully_verified'),
  ('Czech Republic', 'Mojmir Chytil', 66275, 'FW', 'fully_verified'),
  ('Czech Republic', 'Jan Kuchta', 66340, 'FW', 'fully_verified'),
  ('Czech Republic', 'Patrik Schick', 794, 'FW', 'fully_verified'),
  ('South Africa', 'Ronwen Williams', 3275, 'GK', 'fully_verified'),
  ('South Africa', 'Ricardo Goss', 46245, 'GK', 'fully_verified'),
  ('South Africa', 'Sipho Chaine', 46417, 'GK', 'fully_verified'),
  ('South Africa', 'Khuliso Mudau', 46601, 'DF', 'fully_verified'),
  ('South Africa', 'Olwethu Makhanya', 392387, 'DF', 'squad_missing_name_ok'),
  ('South Africa', 'Bradley Cross', 163041, 'DF', 'squad_missing_name_ok'),
  ('South Africa', 'Aubrey Modiba', 46334, 'DF', 'fully_verified'),
  ('South Africa', 'Thabang Matuludi', 330174, 'DF', 'fully_verified'),
  ('South Africa', 'Nkosinathi Sibisi', 46458, 'DF', 'fully_verified'),
  ('South Africa', 'Khulumani Ndamane', -50, 'DF', 'placeholder_lineup_pending'),
  ('South Africa', 'Ime Okon', 406752, 'DF', 'fully_verified'),
  ('South Africa', 'Samukele Kabini', 430078, 'DF', 'squad_ok_name_suspect'),
  ('South Africa', 'Mbekezeli Mbokazi', 510799, 'DF', 'fully_verified'),
  ('South Africa', 'Kamogelo Sebelebele', 359561, 'DF', 'squad_missing_name_ok'),
  ('South Africa', 'Teboho Mokoena', 3287, 'MF', 'fully_verified'),
  ('South Africa', 'Jayden Adams', 268710, 'MF', 'fully_verified'),
  ('South Africa', 'Thalente Mbatha', 194430, 'MF', 'fully_verified'),
  ('South Africa', 'Sphephelo Sithole', 158433, 'MF', 'fully_verified'),
  ('South Africa', 'Oswin Appollis', 179893, 'FW', 'fully_verified'),
  ('South Africa', 'Tshepang Moremi', 295977, 'FW', 'fully_verified'),
  ('South Africa', 'Evidence Makgopa', 201354, 'FW', 'fully_verified'),
  ('South Africa', 'Lyle Foster', 98936, 'FW', 'fully_verified'),
  ('South Africa', 'Iqraam Rayners', 127429, 'FW', 'squad_missing_name_ok'),
  ('South Africa', 'Relebohile Mofokeng', 414149, 'FW', 'fully_verified'),
  ('South Africa', 'Themba Zwane', 3289, 'FW', 'fully_verified'),
  ('South Africa', 'Thapelo Maseko', 354831, 'FW', 'fully_verified'),
  ('Canada', 'Maxime Crepeau', 51274, 'GK', 'fully_verified'),
  ('Canada', 'Owen Goodman', 284554, 'GK', 'fully_verified'),
  ('Canada', 'Dayne St. Clair', 51148, 'GK', 'fully_verified'),
  ('Canada', 'Moise Bombito', 407017, 'DF', 'club_match'),
  ('Canada', 'Derek Cornelius', 51295, 'DF', 'fully_verified'),
  ('Canada', 'Alphonso Davies', 509, 'DF', 'squad_missing_name_ok'),
  ('Canada', 'Luc de Fougerolles', 327738, 'DF', 'fully_verified'),
  ('Canada', 'Alistair Johnston', 78547, 'DF', 'squad_missing_name_ok'),
  ('Canada', 'Alfie Jones', -21, 'DF', 'placeholder_lineup_pending'),
  ('Canada', 'Richie Laryea', 50816, 'DF', 'squad_ok_name_suspect'),
  ('Canada', 'Niko Sigur', 416901, 'DF', 'fully_verified'),
  ('Canada', 'Joel Waterman', 78494, 'DF', 'fully_verified'),
  ('Canada', 'Ali Ahmed', 362145, 'MF', 'fully_verified'),
  ('Canada', 'Tajon Buchanan', 51016, 'MF', 'fully_verified'),
  ('Canada', 'Mathieu Choiniere', 50788, 'MF', 'fully_verified'),
  ('Canada', 'Stephen Eustaquio', 35570, 'MF', 'fully_verified'),
  ('Canada', 'Ismael Kone', 328046, 'MF', 'fully_verified'),
  ('Canada', 'Liam Millar', 44798, 'MF', 'fully_verified'),
  ('Canada', 'Jonathan Osorio', 50817, 'MF', 'fully_verified'),
  ('Canada', 'Nathan-Dylan Saliba', 294824, 'MF', 'fully_verified'),
  ('Canada', 'Jacob Shaffelburg', 50826, 'MF', 'fully_verified'),
  ('Canada', 'Jonathan David', 8489, 'FW', 'fully_verified'),
  ('Canada', 'Promise David', 313353, 'FW', 'fully_verified'),
  ('Canada', 'Cyle Larin', 2001, 'FW', 'fully_verified'),
  ('Canada', 'Tani Oluwaseyi', 351587, 'FW', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Osman Hadzikic', 70480, 'GK', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Nikola Vasilj', 9026, 'GK', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Martin Zlomislic', 108370, 'GK', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Nidal Celik', -20, 'DF', 'placeholder_lineup_pending'),
  ('Bosnia-Herzegovina', 'Amar Dedic', 7318, 'DF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Dennis Hadzikadunic', 53517, 'DF', 'squad_missing_name_ok'),
  ('Bosnia-Herzegovina', 'Nikola Katic', 1741, 'DF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Sead Kolasinac', 1442, 'DF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Tarik Muharemovic', 271350, 'DF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Nihad Mujakic', 76867, 'DF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Stjepan Radeljic', 14301, 'DF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Kerim Alajbegovic', 395559, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Esmir Bajraktarevic', 329409, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Ivan Basic', 162222, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Dzenis Burnic', 25129, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Armina Gigovic', 70514, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Amir Hadziahmetovic', 50006, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Ermin Mahmic', 340173, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Amar Memic', 322101, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Ivan Sunjic', 1324, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Benjamin Tahirovic', 264094, 'MF', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Samed Bazdar', 314377, 'FW', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Ermedin Demirovic', 46930, 'FW', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Edin Dzeko', 790, 'FW', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Jovo Lukic', 77037, 'FW', 'fully_verified'),
  ('Bosnia-Herzegovina', 'Haris Tabakovic', 28382, 'FW', 'fully_verified'),
  ('Qatar', 'Mahmoud Abunada', 42207, 'GK', 'squad_ok_name_suspect'),
  ('Qatar', 'Shehab Al Lithi', 42055, 'GK', 'squad_ok_name_mismatch'),
  ('Qatar', 'Meshaal Barsham', 42021, 'GK', 'fully_verified'),
  ('Qatar', 'Salah Zakaria', 136503, 'GK', 'squad_missing_name_ok'),
  ('Qatar', 'Ryan Al Ali', -84, 'DF', 'placeholder_lineup_pending'),
  ('Qatar', 'Al Hashemi Al Hussein', 42063, 'DF', 'squad_missing_name_flagged'),
  ('Qatar', 'Ayub Al Alawi', -42, 'DF', 'placeholder_lineup_pending'),
  ('Qatar', 'Bassam Al Rawi', 2536, 'DF', 'squad_missing_name_ok'),
  ('Qatar', 'Hommam Al Amin', -43, 'DF', 'placeholder_lineup_pending'),
  ('Qatar', 'Sultan Al Brake', 42060, 'DF', 'squad_ok_name_mismatch'),
  ('Qatar', 'Boualem Khoukhi', 2532, 'DF', 'squad_missing_name_ok'),
  ('Qatar', 'Niall Mason', -46, 'DF', 'placeholder_lineup_pending'),
  ('Qatar', 'Lucas Mendes', 42288, 'DF', 'fully_verified'),
  ('Qatar', 'Pedro Miguel', 2530, 'DF', 'squad_missing_name_ok'),
  ('Qatar', 'Tarek Salman', 2541, 'DF', 'fully_verified'),
  ('Qatar', 'Karim Boudiaf', 2537, 'MF', 'squad_missing_name_ok'),
  ('Qatar', 'Ahmed Fathi', 2539, 'MF', 'fully_verified'),
  ('Qatar', 'Jassem Gaber', 200981, 'MF', 'fully_verified'),
  ('Qatar', 'Abdulaziz Hatem', 2533, 'MF', 'fully_verified'),
  ('Qatar', 'Issa Lay', -44, 'MF', 'placeholder_lineup_pending'),
  ('Qatar', 'Assim Madibo', 2535, 'MF', 'fully_verified'),
  ('Qatar', 'Mohammed Manaai', -45, 'MF', 'placeholder_lineup_pending'),
  ('Qatar', 'Tahsin Mohammed', 2540, 'MF', 'squad_missing_name_flagged'),
  ('Qatar', 'Mohammed Waad', 42180, 'MF', 'fully_verified'),
  ('Qatar', 'Youssef Abdelrisaq', 42421, 'FW', 'squad_ok_name_mismatch'),
  ('Qatar', 'Akram Afif', 2544, 'FW', 'fully_verified'),
  ('Qatar', 'Ahmed Alaaeldin', 2542, 'FW', 'fully_verified'),
  ('Qatar', 'Hassan Al Haydos', 2545, 'FW', 'squad_missing_name_ok'),
  ('Qatar', 'Almoez Ali', 534032, 'FW', 'fully_verified'),
  ('Qatar', 'Ahmed Al Janhi', -41, 'FW', 'placeholder_lineup_pending'),
  ('Qatar', 'Edmilson Junior', 42075, 'FW', 'fully_verified'),
  ('Qatar', 'Mohammed Muntari', 42089, 'FW', 'fully_verified'),
  ('Qatar', 'Mubarak Shannan', 199297, 'FW', 'squad_missing_name_flagged'),
  ('Qatar', 'Sebastian Soria', 42166, 'FW', 'squad_missing_name_ok'),
  ('Switzerland', 'Gregor Kobel', 25282, 'GK', 'fully_verified'),
  ('Switzerland', 'Marvin Keller', 123468, 'GK', 'fully_verified'),
  ('Switzerland', 'Yvon Mvogo', 1142, 'GK', 'fully_verified'),
  ('Switzerland', 'Manuel Akanji', 5, 'DF', 'fully_verified'),
  ('Switzerland', 'Aurele Amenda', 162414, 'DF', 'fully_verified'),
  ('Switzerland', 'Eray Comert', 48372, 'DF', 'fully_verified'),
  ('Switzerland', 'Nico Elvedi', 2803, 'DF', 'fully_verified'),
  ('Switzerland', 'Luca Jaquez', 349344, 'DF', 'fully_verified'),
  ('Switzerland', 'Miro Muheim', 48489, 'DF', 'fully_verified'),
  ('Switzerland', 'Ricardo Rodriguez', 1631, 'DF', 'fully_verified'),
  ('Switzerland', 'Silvan Widmer', 48378, 'DF', 'fully_verified'),
  ('Switzerland', 'Michel Aebischer', 951, 'MF', 'fully_verified'),
  ('Switzerland', 'Christian Fassnacht', 952, 'MF', 'squad_missing_name_ok'),
  ('Switzerland', 'Remo Freuler', 2807, 'MF', 'fully_verified'),
  ('Switzerland', 'Cedric Itten', 48497, 'MF', 'squad_missing_name_ok'),
  ('Switzerland', 'Ardon Jashari', 264705, 'MF', 'fully_verified'),
  ('Switzerland', 'Fabian Rieder', 163032, 'MF', 'fully_verified'),
  ('Switzerland', 'Djibril Sow', 957, 'MF', 'fully_verified'),
  ('Switzerland', 'Granit Xhaka', 1464, 'MF', 'fully_verified'),
  ('Switzerland', 'Denis Zakaria', 2810, 'MF', 'fully_verified'),
  ('Switzerland', 'Zeki Amdouni', 123469, 'FW', 'squad_missing_name_ok'),
  ('Switzerland', 'Breel Embolo', 421, 'FW', 'fully_verified'),
  ('Switzerland', 'Johan Manzambi', 406244, 'FW', 'fully_verified'),
  ('Switzerland', 'Dan Ndoye', 48648, 'FW', 'fully_verified'),
  ('Switzerland', 'Noah Okafor', 48389, 'FW', 'fully_verified'),
  ('Switzerland', 'Ruben Vargas', 48471, 'FW', 'fully_verified'),
  ('Brazil', 'Alisson', 280, 'GK', 'fully_verified'),
  ('Brazil', 'Ederson', 617, 'GK', 'fully_verified'),
  ('Brazil', 'Weverton', 2410, 'GK', 'fully_verified'),
  ('Brazil', 'Alex Sandro', 860, 'DF', 'squad_missing_name_ok'),
  ('Brazil', 'Bremer', 30497, 'DF', 'fully_verified'),
  ('Brazil', 'Danilo', -66, 'DF', 'placeholder_lineup_pending'),
  ('Brazil', 'Douglas Santos', 24866, 'DF', 'fully_verified'),
  ('Brazil', 'Gabriel Magalhães', 22224, 'DF', 'fully_verified'),
  ('Brazil', 'Ibanez', 30424, 'DF', 'fully_verified'),
  ('Brazil', 'Leo Pereira', 10124, 'DF', 'fully_verified'),
  ('Brazil', 'Marquinhos', 257, 'DF', 'fully_verified'),
  ('Brazil', 'Wesley', 349001, 'DF', 'fully_verified'),
  ('Brazil', 'Bruno Guimaraes', 10135, 'MF', 'squad_missing_name_ok'),
  ('Brazil', 'Casemiro', 747, 'MF', 'fully_verified'),
  ('Brazil', 'Danilo Santos', 618, 'MF', 'fully_verified'),
  ('Brazil', 'Fabinho', 299, 'MF', 'fully_verified'),
  ('Brazil', 'Lucas Paqueta', 1646, 'MF', 'squad_missing_name_ok'),
  ('Brazil', 'Endrick', 377122, 'FW', 'fully_verified'),
  ('Brazil', 'Gabriel Martinelli', 127769, 'FW', 'fully_verified'),
  ('Brazil', 'Igor Thiago', 196156, 'FW', 'fully_verified'),
  ('Brazil', 'Luiz Henrique', 265785, 'FW', 'fully_verified'),
  ('Brazil', 'Matheus Cunha', 1165, 'FW', 'fully_verified'),
  ('Brazil', 'Neymar Junior', 276, 'FW', 'fully_verified'),
  ('Brazil', 'Raphinha', 1496, 'FW', 'fully_verified'),
  ('Brazil', 'Rayan', 407806, 'FW', 'fully_verified'),
  ('Brazil', 'Vinicius Junior', 762, 'FW', 'fully_verified'),
  ('Morocco', 'Yassine Bounou', 2701, 'GK', 'fully_verified'),
  ('Morocco', 'Munir El Kajoui', -40, 'GK', 'placeholder_lineup_pending'),
  ('Morocco', 'Reda Tagnaouti', 2703, 'GK', 'club_match'),
  ('Morocco', 'Noussair Mazraoui', 545, 'DF', 'fully_verified'),
  ('Morocco', 'Anass Salah-Eddine', 162451, 'DF', 'fully_verified'),
  ('Morocco', 'Youssef Belammari', 146772, 'DF', 'fully_verified'),
  ('Morocco', 'Achraf Hakimi', 9, 'DF', 'fully_verified'),
  ('Morocco', 'Zakaria El Ouahdi', 283252, 'DF', 'fully_verified'),
  ('Morocco', 'Nayef Aguerd', 21694, 'DF', 'fully_verified'),
  ('Morocco', 'Chadi Riad', 278898, 'DF', 'fully_verified'),
  ('Morocco', 'Redouane Halhal', 326183, 'DF', 'fully_verified'),
  ('Morocco', 'Issa Diop', 18814, 'DF', 'fully_verified'),
  ('Morocco', 'Samir El Mourabet', 415431, 'MF', 'fully_verified'),
  ('Morocco', 'Ayyoub Bouaddi', 438688, 'MF', 'squad_missing_name_ok'),
  ('Morocco', 'Neil El Aynaoui', 277003, 'MF', 'fully_verified'),
  ('Morocco', 'Sofyan Amrabat', 74, 'MF', 'fully_verified'),
  ('Morocco', 'Azzedine Ounahi', 129678, 'MF', 'fully_verified'),
  ('Morocco', 'Bilal El Khannouss', 340573, 'MF', 'fully_verified'),
  ('Morocco', 'Ismael Saibari', 161897, 'MF', 'fully_verified'),
  ('Morocco', 'Abde Ezzalzouli', 181421, 'FW', 'fully_verified'),
  ('Morocco', 'Chemsdine Talbi', 336659, 'FW', 'fully_verified'),
  ('Morocco', 'Soufiane Rahimi', 36579, 'FW', 'fully_verified'),
  ('Morocco', 'Ayoub El Kaabi', 2722, 'FW', 'fully_verified'),
  ('Morocco', 'Brahim Diaz', 744, 'FW', 'fully_verified'),
  ('Morocco', 'Gessime Yassine', 369544, 'FW', 'fully_verified'),
  ('Morocco', 'Ayoube Amaimouni', 535046, 'FW', 'squad_missing_name_ok'),
  ('Scotland', 'Craig Gordon', 147254, 'GK', 'squad_missing_name_flagged'),
  ('Scotland', 'Angus Gunn', 18933, 'GK', 'fully_verified'),
  ('Scotland', 'Liam Kelly', 44937, 'GK', 'fully_verified'),
  ('Scotland', 'Grant Hanley', 19066, 'DF', 'fully_verified'),
  ('Scotland', 'Jack Hendry', 1111, 'DF', 'fully_verified'),
  ('Scotland', 'Aaron Hickey', 44871, 'DF', 'squad_missing_name_ok'),
  ('Scotland', 'Dom Hyam', 19987, 'DF', 'fully_verified'),
  ('Scotland', 'Scott McKenna', 44811, 'DF', 'fully_verified'),
  ('Scotland', 'Nathan Patterson', 138417, 'DF', 'fully_verified'),
  ('Scotland', 'Anthony Ralston', 1115, 'DF', 'fully_verified'),
  ('Scotland', 'Andy Robertson', 289, 'DF', 'squad_ok_name_suspect'),
  ('Scotland', 'John Souttar', 44865, 'DF', 'fully_verified'),
  ('Scotland', 'Kieran Tierney', 1117, 'DF', 'fully_verified'),
  ('Scotland', 'Ryan Christie', 1125, 'MF', 'fully_verified'),
  ('Scotland', 'Findlay Curtis', 433272, 'MF', 'fully_verified'),
  ('Scotland', 'Lewis Ferguson', 44814, 'MF', 'fully_verified'),
  ('Scotland', 'Ben Gannon-Doak', 343576, 'MF', 'club_match'),
  ('Scotland', 'John McGinn', 19191, 'MF', 'fully_verified'),
  ('Scotland', 'Kenny McLean', 19077, 'MF', 'squad_ok_name_suspect'),
  ('Scotland', 'Scott McTominay', 903, 'MF', 'fully_verified'),
  ('Scotland', 'Che Adams', 19524, 'FW', 'fully_verified'),
  ('Scotland', 'Lyndon Dykes', 45307, 'FW', 'fully_verified'),
  ('Scotland', 'George Hirst', 8794, 'FW', 'fully_verified'),
  ('Scotland', 'Lawrence Shankland', 45175, 'FW', 'squad_missing_name_ok'),
  ('Scotland', 'Ross Stewart', 430201, 'FW', 'squad_missing_name_flagged'),
  ('Scotland', 'Tyler Fletcher', -49, 'MF', 'placeholder_lineup_pending'),
  ('Haiti', 'Josue Duverger', 123742, 'GK', 'fully_verified'),
  ('Haiti', 'Alexandre Pierre', 174768, 'GK', 'fully_verified'),
  ('Haiti', 'Johny Placide', 87789, 'GK', 'squad_missing_name_ok'),
  ('Haiti', 'Ricardo Ade', 12303, 'DF', 'fully_verified'),
  ('Haiti', 'Carlens Arcus', 20850, 'DF', 'squad_missing_name_ok'),
  ('Haiti', 'Hannes Delcroix', 1411, 'DF', 'fully_verified'),
  ('Haiti', 'Jean-Kevin Duverne', 20655, 'DF', 'fully_verified'),
  ('Haiti', 'Martin Experience', 190747, 'DF', 'fully_verified'),
  ('Haiti', 'Duke Lacroix', 102505, 'DF', 'squad_ok_name_suspect'),
  ('Haiti', 'Wilguens Paugain', 275367, 'DF', 'fully_verified'),
  ('Haiti', 'Keeto Thermoncy', 573613, 'DF', 'squad_missing_name_ok'),
  ('Haiti', 'Carl Fred Sainte', 540857, 'MF', 'fully_verified'),
  ('Haiti', 'Jean-Ricner Bellegarde', 20665, 'MF', 'fully_verified'),
  ('Haiti', 'Leverton Pierre', 20538, 'MF', 'fully_verified'),
  ('Haiti', 'Danley Jean Jacques', 237292, 'MF', 'squad_missing_name_flagged'),
  ('Haiti', 'Woodensky Pierre', 371050, 'MF', 'fully_verified'),
  ('Haiti', 'Dominique Simon', 194242, 'MF', 'fully_verified'),
  ('Haiti', 'Josue Casimir', 174915, 'FW', 'fully_verified'),
  ('Haiti', 'Louicius Deedson', 128766, 'FW', 'fully_verified'),
  ('Haiti', 'Derrick Etienne Jr.', 50958, 'FW', 'fully_verified'),
  ('Haiti', 'Yassin Fortune', 48535, 'FW', 'fully_verified'),
  ('Haiti', 'Wilson Isidor', 84087, 'FW', 'fully_verified'),
  ('Haiti', 'Lenny Joseph', 21613, 'FW', 'fully_verified'),
  ('Haiti', 'Duckens Nazon', 45020, 'FW', 'fully_verified'),
  ('Haiti', 'Frantzdy Pierrot', 8601, 'FW', 'fully_verified'),
  ('Haiti', 'Ruben Providence', 162733, 'FW', 'fully_verified'),
  ('United States', 'Chris Brady', 266606, 'GK', 'fully_verified'),
  ('United States', 'Matt Freese', 50728, 'GK', 'fully_verified'),
  ('United States', 'Matt Turner', 50999, 'GK', 'fully_verified'),
  ('United States', 'Max Arfsten', 362400, 'DF', 'fully_verified'),
  ('United States', 'Sergino Dest', 38735, 'DF', 'fully_verified'),
  ('United States', 'Alex Freeman', 355994, 'DF', 'fully_verified'),
  ('United States', 'Mark McKenzie', 50735, 'DF', 'fully_verified'),
  ('United States', 'Tim Ream', 19023, 'DF', 'fully_verified'),
  ('United States', 'Chris Richards', 126949, 'DF', 'fully_verified'),
  ('United States', 'Antonee Robinson', 19549, 'DF', 'fully_verified'),
  ('United States', 'Miles Robinson', 50879, 'DF', 'fully_verified'),
  ('United States', 'Joe Scally', 50852, 'DF', 'squad_ok_name_suspect'),
  ('United States', 'Auston Trusty', 50737, 'DF', 'fully_verified'),
  ('United States', 'Tyler Adams', 1150, 'MF', 'lookup_match'),
  ('United States', 'Sebastian Berhalter', 201713, 'MF', 'fully_verified'),
  ('United States', 'Weston McKennie', 415, 'MF', 'fully_verified'),
  ('United States', 'Cristian Roldan', 51114, 'MF', 'fully_verified'),
  ('United States', 'Brenden Aaronson', 50739, 'MF', 'fully_verified'),
  ('United States', 'Christian Pulisic', 17, 'MF', 'fully_verified'),
  ('United States', 'Gio Reyna', 161921, 'MF', 'fully_verified'),
  ('United States', 'Malik Tillman', 162037, 'MF', 'fully_verified'),
  ('United States', 'Timothy Weah', 1138, 'MF', 'fully_verified'),
  ('United States', 'Alejandro Zendejas', 51248, 'MF', 'squad_missing_name_flagged'),
  ('United States', 'Folarin Balogun', 138835, 'FW', 'fully_verified'),
  ('United States', 'Ricardo Pepi', 73868, 'FW', 'fully_verified'),
  ('United States', 'Haji Wright', 427, 'FW', 'fully_verified'),
  ('Paraguay', 'Orlando Gill', 70852, 'GK', 'fully_verified'),
  ('Paraguay', 'Roberto Fernandez', 535737, 'GK', 'squad_missing_name_ok'),
  ('Paraguay', 'Gaston Olveira', 51733, 'GK', 'fully_verified'),
  ('Paraguay', 'Juan Cáceres', 195992, 'DF', 'fully_verified'),
  ('Paraguay', 'Gustavo Velázquez', 35808, 'DF', 'fully_verified'),
  ('Paraguay', 'Gustavo Gómez', 2502, 'DF', 'fully_verified'),
  ('Paraguay', 'Junior Alonso', 2499, 'DF', 'fully_verified'),
  ('Paraguay', 'Jose Canale', 70732, 'DF', 'fully_verified'),
  ('Paraguay', 'Omar Alderete', 6168, 'DF', 'fully_verified'),
  ('Paraguay', 'Alexandro Maidana', 425020, 'DF', 'fully_verified'),
  ('Paraguay', 'Fabian Balbuena', 2500, 'DF', 'fully_verified'),
  ('Paraguay', 'Diego Gómez', 278370, 'MF', 'fully_verified'),
  ('Paraguay', 'Mauricio Magalhães', 106485, 'MF', 'fully_verified'),
  ('Paraguay', 'Damián Bobadilla', 195107, 'MF', 'fully_verified'),
  ('Paraguay', 'Braian Ojeda', 70767, 'MF', 'fully_verified'),
  ('Paraguay', 'Andrés Cubas', 6236, 'MF', 'fully_verified'),
  ('Paraguay', 'Matías Galarza', 305832, 'MF', 'fully_verified'),
  ('Paraguay', 'Alejandro Gamarra', -19, 'MF', 'placeholder_lineup_pending'),
  ('Paraguay', 'Gustavo Caballero', 119128, 'FW', 'fully_verified'),
  ('Paraguay', 'Ramón Sosa', 196298, 'FW', 'fully_verified'),
  ('Paraguay', 'Alex Arce', 95460, 'FW', 'fully_verified'),
  ('Paraguay', 'Isidro Pitta', 70670, 'FW', 'fully_verified'),
  ('Paraguay', 'Gabriel Ávalos', 6483, 'FW', 'fully_verified'),
  ('Paraguay', 'Miguel Almirón', 2507, 'FW', 'fully_verified'),
  ('Paraguay', 'Julio Enciso', 70747, 'FW', 'fully_verified'),
  ('Paraguay', 'Antonio Sanabria', 2522, 'FW', 'fully_verified'),
  ('Turkey', 'Altay Bayindir', 380507, 'GK', 'squad_missing_name_flagged'),
  ('Turkey', 'Ersin Destanoglu', 1971, 'GK', 'fully_verified'),
  ('Turkey', 'Mert Gunok', 49837, 'GK', 'fully_verified'),
  ('Turkey', 'Muhammed Sengezer', 50218, 'GK', 'fully_verified'),
  ('Turkey', 'Ugurcan Cakir', 49866, 'GK', 'club_match'),
  ('Turkey', 'Abdulkerim Bardakci', 61837, 'DF', 'club_match'),
  ('Turkey', 'Ahmetcan Kaplan', 278159, 'DF', 'fully_verified'),
  ('Turkey', 'Caglar Soyuncu', 18776, 'DF', 'fully_verified'),
  ('Turkey', 'Eren Elmali', 50057, 'DF', 'club_match'),
  ('Turkey', 'Ferdi Kadioglu', 1361, 'DF', 'club_match'),
  ('Turkey', 'Merih Demiral', -57, 'DF', 'placeholder_lineup_pending'),
  ('Turkey', 'Mert Muldur', 1719, 'DF', 'fully_verified'),
  ('Turkey', 'Mustafa Eskihellac', 62323, 'DF', 'squad_missing_name_ok'),
  ('Turkey', 'Ozan Kabak', 26300, 'DF', 'fully_verified'),
  ('Turkey', 'Samet Akaydin', 62490, 'DF', 'fully_verified'),
  ('Turkey', 'Yusuf Akcicek', -83, 'DF', 'placeholder_lineup_pending'),
  ('Turkey', 'Zeki Celik', 22222, 'DF', 'fully_verified'),
  ('Turkey', 'Atakan Karazor', 24963, 'MF', 'fully_verified'),
  ('Turkey', 'Demir Ege Tiknaz', -56, 'MF', 'placeholder_lineup_pending'),
  ('Turkey', 'Hakan Calhanoglu', 1640, 'MF', 'fully_verified'),
  ('Turkey', 'Ismail Yuksek', 214463, 'MF', 'fully_verified'),
  ('Turkey', 'Kaan Ayhan', 25448, 'MF', 'fully_verified'),
  ('Turkey', 'Orkun Kokcu', 37155, 'MF', 'fully_verified'),
  ('Turkey', 'Salih Ozcan', 24807, 'MF', 'fully_verified'),
  ('Turkey', 'Aral Simsir', 161790, 'FW', 'fully_verified'),
  ('Turkey', 'Arda Guler', 291964, 'FW', 'fully_verified'),
  ('Turkey', 'Baris Alper Yilmaz', 63274, 'FW', 'club_match'),
  ('Turkey', 'Can Uzun', 339887, 'FW', 'fully_verified'),
  ('Turkey', 'Deniz Gul', 388570, 'FW', 'fully_verified'),
  ('Turkey', 'Irfan Can Kahveci', 49857, 'FW', 'fully_verified'),
  ('Turkey', 'Kenan Yildiz', 339883, 'FW', 'club_match'),
  ('Turkey', 'Kerem Akturkoglu', 142959, 'FW', 'fully_verified'),
  ('Turkey', 'Oguz Aydin', 222557, 'FW', 'lookup_match'),
  ('Turkey', 'Yunus Akgun', 454, 'FW', 'fully_verified'),
  ('Turkey', 'Yusuf Sari', 412703, 'FW', 'fully_verified'),
  ('Australia', 'Patrick Beach', 353883, 'GK', 'fully_verified'),
  ('Australia', 'Paul Izzo', 6870, 'GK', 'fully_verified'),
  ('Australia', 'Mathew Ryan', 2741, 'GK', 'fully_verified'),
  ('Australia', 'Aziz Behich', 225, 'DF', 'fully_verified'),
  ('Australia', 'Jordan Bos', 337587, 'DF', 'fully_verified'),
  ('Australia', 'Cameron Burgess', 20457, 'DF', 'fully_verified'),
  ('Australia', 'Alessandro Circati', 348568, 'DF', 'fully_verified'),
  ('Australia', 'Milos Degenek', 2742, 'DF', 'fully_verified'),
  ('Australia', 'Jason Geria', 33847, 'DF', 'fully_verified'),
  ('Australia', 'Lucas Herrington', 426480, 'DF', 'fully_verified'),
  ('Australia', 'Jacob Italiano', 6808, 'DF', 'fully_verified'),
  ('Australia', 'Harry Souttar', 20079, 'DF', 'squad_missing_name_ok'),
  ('Australia', 'Kai Trewin', 153622, 'DF', 'fully_verified'),
  ('Australia', 'Cameron Devlin', 6832, 'MF', 'squad_missing_name_ok'),
  ('Australia', 'Ajdin Hrustić', 38123, 'MF', 'fully_verified'),
  ('Australia', 'Jackson Irvine', 2749, 'MF', 'squad_missing_name_ok'),
  ('Australia', 'Connor Metcalfe', 6904, 'MF', 'fully_verified'),
  ('Australia', 'Paul Okon-Engstler', 441269, 'MF', 'fully_verified'),
  ('Australia', 'Aiden O''Neill', 7050, 'MF', 'fully_verified'),
  ('Australia', 'Nestory Irankunda', 338014, 'FW', 'fully_verified'),
  ('Australia', 'Mathew Leckie', 2751, 'FW', 'squad_missing_name_ok'),
  ('Australia', 'Awer Mabil', 2755, 'FW', 'fully_verified'),
  ('Australia', 'Mohamed Touré', 198352, 'FW', 'squad_missing_name_ok'),
  ('Australia', 'Nishan Velupillay', 312459, 'FW', 'fully_verified'),
  ('Australia', 'Cristian Volpato', 342035, 'FW', 'squad_missing_name_ok'),
  ('Australia', 'Tete Yengi', 296645, 'FW', 'squad_missing_name_ok'),
  ('Germany', 'Oliver Baumann', 702, 'GK', 'fully_verified'),
  ('Germany', 'Manuel Neuer', 497, 'GK', 'fully_verified'),
  ('Germany', 'Alexander Nubel', 399, 'GK', 'fully_verified'),
  ('Germany', 'Waldemar Anton', 25368, 'DF', 'fully_verified'),
  ('Germany', 'Nathaniel Brown', 280074, 'DF', 'fully_verified'),
  ('Germany', 'Joshua Kimmich', 502, 'DF', 'fully_verified'),
  ('Germany', 'David Raum', 25158, 'DF', 'fully_verified'),
  ('Germany', 'Antonio Rudiger', 2285, 'DF', 'fully_verified'),
  ('Germany', 'Nico Schlotterbeck', 26243, 'DF', 'fully_verified'),
  ('Germany', 'Jonathan Tah', 972, 'DF', 'fully_verified'),
  ('Germany', 'Malick Thiaw', 163189, 'DF', 'fully_verified'),
  ('Germany', 'Nadiem Amiri', 714, 'MF', 'fully_verified'),
  ('Germany', 'Leon Goretzka', 511, 'MF', 'fully_verified'),
  ('Germany', 'Pascal Gross', 18970, 'MF', 'club_match'),
  ('Germany', 'Lennart Karl', 494131, 'MF', 'fully_verified'),
  ('Germany', 'Jamie Leweling', 128533, 'MF', 'fully_verified'),
  ('Germany', 'Jamal Musiala', 181812, 'MF', 'fully_verified'),
  ('Germany', 'Felix Nmecha', 637, 'MF', 'fully_verified'),
  ('Germany', 'Aleksandar Pavlovic', 328033, 'MF', 'fully_verified'),
  ('Germany', 'Leroy Sane', 644, 'MF', 'fully_verified'),
  ('Germany', 'Angelo Stiller', 137210, 'MF', 'fully_verified'),
  ('Germany', 'Florian Wirtz', 203224, 'MF', 'fully_verified'),
  ('Germany', 'Maximilian Beier', 301027, 'FW', 'squad_missing_name_flagged'),
  ('Germany', 'Kai Havertz', 978, 'FW', 'fully_verified'),
  ('Germany', 'Deniz Undav', 26475, 'FW', 'fully_verified'),
  ('Germany', 'Nick Woltemade', 158054, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Yahia Fofana', 64190, 'GK', 'fully_verified'),
  ('Ivory Coast', 'Mohamed Kone', 277046, 'GK', 'fully_verified'),
  ('Ivory Coast', 'Alban Lafont', 30393, 'GK', 'fully_verified'),
  ('Ivory Coast', 'Emmanuel Agbadou', 135068, 'DF', 'fully_verified'),
  ('Ivory Coast', 'Christopher Operi', 20836, 'DF', 'squad_missing_name_ok'),
  ('Ivory Coast', 'Ousmane Diomande', 354753, 'DF', 'fully_verified'),
  ('Ivory Coast', 'Guela Doue', 161747, 'DF', 'fully_verified'),
  ('Ivory Coast', 'Ghislain Konan', 22002, 'DF', 'fully_verified'),
  ('Ivory Coast', 'Odilon Kossounou', 48119, 'DF', 'fully_verified'),
  ('Ivory Coast', 'Wilfried Singo', 30504, 'DF', 'fully_verified'),
  ('Ivory Coast', 'Evan Ndicka', 1807, 'DF', 'fully_verified'),
  ('Ivory Coast', 'Seko Fofana', 30807, 'MF', 'fully_verified'),
  ('Ivory Coast', 'Parfait Guiagon', 263228, 'MF', 'fully_verified'),
  ('Ivory Coast', 'Christ Inao Oulai', 474591, 'MF', 'fully_verified'),
  ('Ivory Coast', 'Franck Kessie', 1642, 'MF', 'fully_verified'),
  ('Ivory Coast', 'Ibrahim Sangare', 22149, 'MF', 'fully_verified'),
  ('Ivory Coast', 'Jean Michael Seri', 3243, 'MF', 'fully_verified'),
  ('Ivory Coast', 'Simon Adingra', 301771, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Ange-Yoan Bonny', 275651, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Amad Diallo', 157997, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Oumar Diakite', 334429, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Yan Diomande', 513776, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Evann Guessand', 137303, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Nicolas Pepe', 3246, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Bazoumana Toure', 387643, 'FW', 'fully_verified'),
  ('Ivory Coast', 'Elye Wahi', 162707, 'FW', 'fully_verified'),
  ('Ecuador', 'Hernán Galíndez', 16380, 'GK', 'fully_verified'),
  ('Ecuador', 'Gonzalo Valle', 16642, 'GK', 'fully_verified'),
  ('Ecuador', 'Moisés Ramírez', 81224, 'GK', 'squad_ok_name_suspect'),
  ('Ecuador', 'Piero Hincapié', 127817, 'DF', 'fully_verified'),
  ('Ecuador', 'Willian Pacho', 16367, 'DF', 'fully_verified'),
  ('Ecuador', 'Pervis Estupiñán', 46731, 'DF', 'fully_verified'),
  ('Ecuador', 'Ángelo Preciado', 2583, 'DF', 'fully_verified'),
  ('Ecuador', 'Joel Ordóñez', 354027, 'DF', 'fully_verified'),
  ('Ecuador', 'Félix Torres', 63964, 'DF', 'fully_verified'),
  ('Ecuador', 'Jackson Porozo', 2575, 'DF', 'fully_verified'),
  ('Ecuador', 'Yaimar Medina', 306940, 'DF', 'fully_verified'),
  ('Ecuador', 'Moisés Caicedo', 116117, 'MF', 'fully_verified'),
  ('Ecuador', 'Alan Franco', 16360, 'MF', 'fully_verified'),
  ('Ecuador', 'Gonzalo Plata', 16369, 'MF', 'fully_verified'),
  ('Ecuador', 'Kendry Páez', 406303, 'MF', 'squad_ok_name_suspect'),
  ('Ecuador', 'Pedro Vite', 237078, 'MF', 'fully_verified'),
  ('Ecuador', 'Jordy Alcívar', 16470, 'MF', 'fully_verified'),
  ('Ecuador', 'Denil Castillo', 338045, 'MF', 'fully_verified'),
  ('Ecuador', 'John Yeboah', 25414, 'MF', 'fully_verified'),
  ('Ecuador', 'Nilson Angulo', 311543, 'MF', 'fully_verified'),
  ('Ecuador', 'Alan Minda', 280695, 'MF', 'fully_verified'),
  ('Ecuador', 'Enner Valencia', 35533, 'FW', 'fully_verified'),
  ('Ecuador', 'Kevin Rodríguez', 361966, 'FW', 'fully_verified'),
  ('Ecuador', 'Jordy Caicedo', 16590, 'FW', 'fully_verified'),
  ('Ecuador', 'Anthony Valencia', 198347, 'FW', 'fully_verified'),
  ('Ecuador', 'Jeremy Arévalo', 350799, 'FW', 'fully_verified'),
  ('Curaçao', 'Tyrick Bodack', -22, 'GK', 'placeholder_lineup_pending'),
  ('Curaçao', 'Trevor Doornbusch', 36967, 'GK', 'fully_verified'),
  ('Curaçao', 'Eloy Room', 221, 'GK', 'fully_verified'),
  ('Curaçao', 'Riechedly Bazoer', 37175, 'DF', 'fully_verified'),
  ('Curaçao', 'Joshua Brenet', 706, 'DF', 'fully_verified'),
  ('Curaçao', 'Roshon van Eijma', 37066, 'DF', 'fully_verified'),
  ('Curaçao', 'Sherel Floranus', 36970, 'DF', 'fully_verified'),
  ('Curaçao', 'Deveron Fonville', 353808, 'DF', 'fully_verified'),
  ('Curaçao', 'Jurien Gaari', 36857, 'DF', 'fully_verified'),
  ('Curaçao', 'Armando Obispo', 228, 'DF', 'squad_missing_name_ok'),
  ('Curaçao', 'Shurandy Sambo', 194645, 'DF', 'fully_verified'),
  ('Curaçao', 'Juninho Bacuna', 19047, 'MF', 'fully_verified'),
  ('Curaçao', 'Leandro Bacuna', 18997, 'MF', 'fully_verified'),
  ('Curaçao', 'Livano Comenencia', 309763, 'MF', 'fully_verified'),
  ('Curaçao', 'Kevin Felida', 37461, 'MF', 'fully_verified'),
  ('Curaçao', 'Ar''jany Martha', 162199, 'MF', 'fully_verified'),
  ('Curaçao', 'Tyrese Noslin', 406846, 'MF', 'fully_verified'),
  ('Curaçao', 'Godfried Roemeratoe', 36842, 'MF', 'fully_verified'),
  ('Curaçao', 'Jeremy Antonisse', 163220, 'FW', 'fully_verified'),
  ('Curaçao', 'Tahith Chong', 906, 'FW', 'fully_verified'),
  ('Curaçao', 'Kenji Gorre', 41627, 'FW', 'fully_verified'),
  ('Curaçao', 'Sontje Hansen', 161884, 'FW', 'fully_verified'),
  ('Curaçao', 'Gervane Kastaneer', 38708, 'FW', 'fully_verified'),
  ('Curaçao', 'Brandley Kuwas', 37272, 'FW', 'fully_verified'),
  ('Curaçao', 'Jurgen Locadia', 18981, 'FW', 'fully_verified'),
  ('Curaçao', 'Jearl Margaritha', 195067, 'FW', 'fully_verified'),
  ('Netherlands', 'Mark Flekken', 26232, 'GK', 'fully_verified'),
  ('Netherlands', 'Robin Roefs', 194536, 'GK', 'squad_missing_name_ok'),
  ('Netherlands', 'Bart Verbruggen', 129058, 'GK', 'fully_verified'),
  ('Netherlands', 'Nathan Ake', 18861, 'DF', 'fully_verified'),
  ('Netherlands', 'Denzel Dumfries', 226, 'DF', 'fully_verified'),
  ('Netherlands', 'Jorrel Hato', 341642, 'DF', 'fully_verified'),
  ('Netherlands', 'Jurrien Timber', -71, 'DF', 'placeholder_lineup_pending'),
  ('Netherlands', 'Jan Paul van Hecke', 38695, 'DF', 'fully_verified'),
  ('Netherlands', 'Virgil van Dijk', 290, 'DF', 'fully_verified'),
  ('Netherlands', 'Micky van de Ven', 152849, 'DF', 'fully_verified'),
  ('Netherlands', 'Frenkie de Jong', 37524, 'MF', 'squad_missing_name_flagged'),
  ('Netherlands', 'Marten de Roon', 30432, 'MF', 'squad_missing_name_ok'),
  ('Netherlands', 'Ryan Gravenberch', 542, 'MF', 'fully_verified'),
  ('Netherlands', 'Teun Koopmeiners', 36899, 'MF', 'fully_verified'),
  ('Netherlands', 'Tijjani Reijnders', 36902, 'MF', 'fully_verified'),
  ('Netherlands', 'Guus Til', 36905, 'MF', 'club_match'),
  ('Netherlands', 'Quinten Timber', 38747, 'MF', 'squad_ok_name_suspect'),
  ('Netherlands', 'Mats Wieffer', 92993, 'MF', 'squad_missing_name_ok'),
  ('Netherlands', 'Brian Brobbey', 38750, 'FW', 'fully_verified'),
  ('Netherlands', 'Memphis Depay', 667, 'FW', 'squad_missing_name_ok'),
  ('Netherlands', 'Cody Gakpo', 247, 'FW', 'fully_verified'),
  ('Netherlands', 'Justin Kluivert', 792, 'FW', 'squad_missing_name_ok'),
  ('Netherlands', 'Noa Lang', 544, 'FW', 'fully_verified'),
  ('Netherlands', 'Donyell Malen', 249, 'FW', 'fully_verified'),
  ('Netherlands', 'Crysencio Summerville', 37724, 'FW', 'squad_missing_name_ok'),
  ('Netherlands', 'Wout Weghorst', 25416, 'FW', 'fully_verified'),
  ('Japan', 'Tomoki Hayakawa', 304782, 'GK', 'fully_verified'),
  ('Japan', 'Keisuke Osako', 33034, 'GK', 'fully_verified'),
  ('Japan', 'Zion Suzuki', 199578, 'GK', 'fully_verified'),
  ('Japan', 'Ko Itakura', 38114, 'DF', 'squad_missing_name_ok'),
  ('Japan', 'Hiroki Ito', 32893, 'DF', 'fully_verified'),
  ('Japan', 'Yuto Nagatomo', 440, 'DF', 'fully_verified'),
  ('Japan', 'Ayumu Seko', 33165, 'DF', 'fully_verified'),
  ('Japan', 'Yukinari Sugawara', 32887, 'DF', 'fully_verified'),
  ('Japan', 'Junnosuke Suzuki', 351014, 'DF', 'fully_verified'),
  ('Japan', 'Shogo Taniguchi', 32954, 'DF', 'fully_verified'),
  ('Japan', 'Takehiro Tomiyasu', 2597, 'DF', 'fully_verified'),
  ('Japan', 'Tsuyoshi Watanabe', 32858, 'DF', 'fully_verified'),
  ('Japan', 'Ritsu Doan', 2598, 'MF', 'fully_verified'),
  ('Japan', 'Wataru Endo', 8500, 'MF', 'squad_missing_name_ok'),
  ('Japan', 'Junya Ito', 1942, 'MF', 'fully_verified'),
  ('Japan', 'Daichi Kamada', 2601, 'MF', 'fully_verified'),
  ('Japan', 'Takefusa Kubo', 32862, 'MF', 'squad_missing_name_ok'),
  ('Japan', 'Keito Nakamura', 33321, 'MF', 'fully_verified'),
  ('Japan', 'Kaishu Sano', 33889, 'MF', 'fully_verified'),
  ('Japan', 'Ao Tanaka', 33142, 'MF', 'squad_ok_name_suspect'),
  ('Japan', 'Keisuke Goto', 375930, 'FW', 'fully_verified'),
  ('Japan', 'Daizen Maeda', 33224, 'FW', 'fully_verified'),
  ('Japan', 'Koki Ogawa', 33289, 'FW', 'fully_verified'),
  ('Japan', 'Kento Shiogai', 422572, 'FW', 'fully_verified'),
  ('Japan', 'Yuito Suzuki', 199143, 'FW', 'fully_verified'),
  ('Japan', 'Ayase Ueda', 72155, 'FW', 'fully_verified'),
  ('Sweden', 'Viktor Johansson', 161223, 'GK', 'squad_missing_name_ok'),
  ('Sweden', 'Gustaf Lagerbielke', 137721, 'GK', 'fully_verified'),
  ('Sweden', 'Kristoffer Nordfeldt', 2851, 'GK', 'fully_verified'),
  ('Sweden', 'Jacob Zetterstrom', 48033, 'GK', 'squad_missing_name_ok'),
  ('Sweden', 'Hjalmar Ekdal', 47903, 'DF', 'fully_verified'),
  ('Sweden', 'Gabriel Gudmundsson', 47969, 'DF', 'fully_verified'),
  ('Sweden', 'Isak Hien', 137976, 'DF', 'fully_verified'),
  ('Sweden', 'Victor Lindelof', 889, 'DF', 'fully_verified'),
  ('Sweden', 'Eric Smith', 8486, 'DF', 'fully_verified'),
  ('Sweden', 'Carl Starfelt', 47988, 'DF', 'fully_verified'),
  ('Sweden', 'Daniel Svensson', 198654, 'DF', 'fully_verified'),
  ('Sweden', 'Yasin Ayari', 265820, 'MF', 'fully_verified'),
  ('Sweden', 'Lucas Bergvall', 347316, 'MF', 'fully_verified'),
  ('Sweden', 'Jesper Karlstrom', 48047, 'MF', 'fully_verified'),
  ('Sweden', 'Benjamin Nygren', 48002, 'MF', 'fully_verified'),
  ('Sweden', 'Ken Sema', 2860, 'MF', 'fully_verified'),
  ('Sweden', 'Elliot Stroud', 226765, 'MF', 'fully_verified'),
  ('Sweden', 'Mattias Svanberg', 30484, 'MF', 'fully_verified'),
  ('Sweden', 'Besfort Zeneli', 350850, 'MF', 'fully_verified'),
  ('Sweden', 'Taha Ali', 160925, 'FW', 'fully_verified'),
  ('Sweden', 'Alexander Bernhardsson', 47696, 'FW', 'squad_missing_name_ok'),
  ('Sweden', 'Anthony Elanga', 153430, 'FW', 'fully_verified'),
  ('Sweden', 'Viktor Gyokeres', 18979, 'FW', 'fully_verified'),
  ('Sweden', 'Alexander Isak', 2864, 'FW', 'squad_missing_name_ok'),
  ('Sweden', 'Gustaf Nilsson', 15683, 'FW', 'fully_verified'),
  ('Tunisia', 'Sabri Ben Hassan', -55, 'GK', 'placeholder_lineup_pending'),
  ('Tunisia', 'Abdelmouhib Chamakh', 533394, 'GK', 'fully_verified'),
  ('Tunisia', 'Aymen Dahmene', -53, 'GK', 'placeholder_lineup_pending'),
  ('Tunisia', 'Ali Abdi', 49583, 'DF', 'fully_verified'),
  ('Tunisia', 'Mohamed Amine Ben Hamida', -54, 'DF', 'placeholder_lineup_pending'),
  ('Tunisia', 'Adem Arous', 393977, 'DF', 'squad_ok_name_suspect'),
  ('Tunisia', 'Dylan Bronn', 2945, 'DF', 'fully_verified'),
  ('Tunisia', 'Raed Chikhaoui', 533360, 'DF', 'fully_verified'),
  ('Tunisia', 'Moutaz Neffati', 375608, 'DF', 'fully_verified'),
  ('Tunisia', 'Omar Rekik', 163068, 'DF', 'fully_verified'),
  ('Tunisia', 'Montassar Talbi', 50030, 'DF', 'fully_verified'),
  ('Tunisia', 'Yan Valery', 18942, 'DF', 'fully_verified'),
  ('Tunisia', 'Mortadha Ben Ouanes', 49469, 'MF', 'fully_verified'),
  ('Tunisia', 'Anis Ben Slimane', 199310, 'MF', 'fully_verified'),
  ('Tunisia', 'Ismael Gharbi', 310196, 'MF', 'fully_verified'),
  ('Tunisia', 'Rani Khedira', 25300, 'MF', 'fully_verified'),
  ('Tunisia', 'Hadj Mahmoud', 67195, 'MF', 'fully_verified'),
  ('Tunisia', 'Hannibal Mejbri', 180560, 'MF', 'fully_verified'),
  ('Tunisia', 'Ellyes Skhiri', 21587, 'MF', 'fully_verified'),
  ('Tunisia', 'Elias Achouri', 42012, 'FW', 'fully_verified'),
  ('Tunisia', 'Khalil Ayari', 533295, 'FW', 'fully_verified'),
  ('Tunisia', 'Firas Chaouat', 2962, 'FW', 'fully_verified'),
  ('Tunisia', 'Rayan Elloumi', 566059, 'FW', 'fully_verified'),
  ('Tunisia', 'Hazem Mastouri', 344862, 'FW', 'fully_verified'),
  ('Tunisia', 'Elias Saad', 323974, 'FW', 'fully_verified'),
  ('Tunisia', 'Sebastian Tounekti', 57518, 'FW', 'fully_verified'),
  ('Belgium', 'Thibaut Courtois', 730, 'GK', 'fully_verified'),
  ('Belgium', 'Senne Lammens', 162511, 'GK', 'fully_verified'),
  ('Belgium', 'Mike Penders', 340151, 'GK', 'fully_verified'),
  ('Belgium', 'Timothy Castagne', 2920, 'DF', 'fully_verified'),
  ('Belgium', 'Zeno Debast', 304228, 'DF', 'fully_verified'),
  ('Belgium', 'Maxim De Cuyper', 162007, 'DF', 'fully_verified'),
  ('Belgium', 'Koni De Winter', 162141, 'DF', 'fully_verified'),
  ('Belgium', 'Brandon Mechele', 69, 'DF', 'fully_verified'),
  ('Belgium', 'Thomas Meunier', 264, 'DF', 'fully_verified'),
  ('Belgium', 'Nathan Ngoy', 312964, 'DF', 'fully_verified'),
  ('Belgium', 'Joaquin Seys', 375974, 'DF', 'fully_verified'),
  ('Belgium', 'Arthur Theate', 204043, 'DF', 'fully_verified'),
  ('Belgium', 'Kevin De Bruyne', 629, 'MF', 'fully_verified'),
  ('Belgium', 'Amadou Onana', 162714, 'MF', 'fully_verified'),
  ('Belgium', 'Nicolas Raskin', 2120, 'MF', 'fully_verified'),
  ('Belgium', 'Youri Tielemans', 2926, 'MF', 'fully_verified'),
  ('Belgium', 'Hans Vanaken', 78, 'MF', 'squad_missing_name_ok'),
  ('Belgium', 'Axel Witsel', 20, 'MF', 'fully_verified'),
  ('Belgium', 'Charles De Ketelaere', 147859, 'FW', 'fully_verified'),
  ('Belgium', 'Jeremy Doku', 1422, 'FW', 'fully_verified'),
  ('Belgium', 'Matias Fernandez-Pardo', 340077, 'FW', 'fully_verified'),
  ('Belgium', 'Romelu Lukaku', 907, 'FW', 'fully_verified'),
  ('Belgium', 'Dodi Lukebakio', 25458, 'FW', 'fully_verified'),
  ('Belgium', 'Diego Moreira', 335056, 'FW', 'fully_verified'),
  ('Belgium', 'Alexis Saelemekars', 1417, 'FW', 'club_match'),
  ('Belgium', 'Leandro Trossard', 1946, 'FW', 'squad_missing_name_ok'),
  ('Iran', 'Alireza Beiranvand', 2682, 'GK', 'fully_verified'),
  ('Iran', 'Hossein Hosseini', 29755, 'GK', 'fully_verified'),
  ('Iran', 'Payam Niazmand', 2681, 'GK', 'fully_verified'),
  ('Iran', 'Daniyal Eiri', -28, 'DF', 'placeholder_lineup_pending'),
  ('Iran', 'Ehsan Hajsafi', -30, 'DF', 'placeholder_lineup_pending'),
  ('Iran', 'Saleh Hardani', 136880, 'DF', 'fully_verified'),
  ('Iran', 'Hossein Kanaani', -31, 'DF', 'placeholder_lineup_pending'),
  ('Iran', 'Shoja Khalilzadeh', 29704, 'DF', 'fully_verified'),
  ('Iran', 'Milad Mohammadi', 2688, 'DF', 'fully_verified'),
  ('Iran', 'Ali Nemati', 533035, 'DF', 'fully_verified'),
  ('Iran', 'Ramin Rezaeian', 2691, 'DF', 'fully_verified'),
  ('Iran', 'Rouzbeh Cheshmi', 2683, 'MF', 'squad_missing_name_flagged'),
  ('Iran', 'Saeid Ezatolahi', 19614, 'MF', 'squad_missing_name_flagged'),
  ('Iran', 'Mehdi Ghayedi', 29781, 'MF', 'squad_missing_name_ok'),
  ('Iran', 'Saman Ghoddos', 2699, 'MF', 'fully_verified'),
  ('Iran', 'Mohammad Ghorbani', 341844, 'MF', 'fully_verified'),
  ('Iran', 'Alireza Jahanbakhsh', 2700, 'MF', 'fully_verified'),
  ('Iran', 'Mohammad Mohebi', 134217, 'MF', 'fully_verified'),
  ('Iran', 'Amir Mohammad Razzaghinia', 423753, 'MF', 'fully_verified'),
  ('Iran', 'Mehdi Torabi', 2697, 'MF', 'squad_missing_name_ok'),
  ('Iran', 'Aria Yousefi', 343405, 'MF', 'fully_verified'),
  ('Iran', 'Ali Alipour', 29720, 'FW', 'fully_verified'),
  ('Iran', 'Dennis Dargahi', -29, 'FW', 'placeholder_lineup_pending'),
  ('Iran', 'Amirhossein Hosseinzadeh', 29937, 'FW', 'fully_verified'),
  ('Iran', 'Mehdi Taremi', 42315, 'FW', 'fully_verified'),
  ('Iran', 'Shahriyar Moghanlou', 89982, 'FW', 'lookup_match'),
  ('New Zealand', 'Max Crocombe', 18110, 'GK', 'fully_verified'),
  ('New Zealand', 'Alex Paulsen', 94360, 'GK', 'fully_verified'),
  ('New Zealand', 'Michael Woud', 36777, 'GK', 'fully_verified'),
  ('New Zealand', 'Tyler Bindon', 430835, 'DF', 'fully_verified'),
  ('New Zealand', 'Michael Boxall', 51149, 'DF', 'fully_verified'),
  ('New Zealand', 'Liberato Cacace', 6931, 'DF', 'fully_verified'),
  ('New Zealand', 'Francis de Vries', 94405, 'DF', 'fully_verified'),
  ('New Zealand', 'Callan Elliot', 6932, 'DF', 'fully_verified'),
  ('New Zealand', 'Tim Payne', 94346, 'DF', 'fully_verified'),
  ('New Zealand', 'Nando Pijnaker', 94344, 'DF', 'fully_verified'),
  ('New Zealand', 'Tommy Smith', 51307, 'DF', 'squad_ok_name_suspect'),
  ('New Zealand', 'Finn Surman', 210165, 'DF', 'fully_verified'),
  ('New Zealand', 'Lachlan Bayliss', 405957, 'MF', 'fully_verified'),
  ('New Zealand', 'Joe Bell', 94541, 'MF', 'fully_verified'),
  ('New Zealand', 'Matt Garbett', 180455, 'MF', 'fully_verified'),
  ('New Zealand', 'Eli Just', 94333, 'MF', 'fully_verified'),
  ('New Zealand', 'Callum McCowatt', 94322, 'MF', 'fully_verified'),
  ('New Zealand', 'Ben Old', 179856, 'MF', 'fully_verified'),
  ('New Zealand', 'Alex Rufer', 6934, 'MF', 'fully_verified'),
  ('New Zealand', 'Marko Stamenic', 179862, 'MF', 'fully_verified'),
  ('New Zealand', 'Sarpreet Singh', 6935, 'MF', 'fully_verified'),
  ('New Zealand', 'Ryan Thomas', 242, 'MF', 'fully_verified'),
  ('New Zealand', 'Kosta Barbarouses', 6865, 'FW', 'squad_ok_name_suspect'),
  ('New Zealand', 'Jesse Randall', 158688, 'FW', 'fully_verified'),
  ('New Zealand', 'Ben Waine', 6938, 'FW', 'fully_verified'),
  ('New Zealand', 'Chris Wood', 18931, 'FW', 'fully_verified'),
  ('Egypt', 'Mohamed Alaa', 550469, 'GK', 'fully_verified'),
  ('Egypt', 'Mohamed El Shenawy', 16797, 'GK', 'fully_verified'),
  ('Egypt', 'Mostafa Shobeir', 269174, 'GK', 'fully_verified'),
  ('Egypt', 'El Mahdy Soliman', 16831, 'GK', 'squad_ok_name_suspect'),
  ('Egypt', 'Hossam Abdelmagid', 269621, 'DF', 'squad_ok_name_mismatch'),
  ('Egypt', 'Mohamed Abdelmonem', 196343, 'DF', 'fully_verified'),
  ('Egypt', 'Tarek Alaa', 550371, 'DF', 'fully_verified'),
  ('Egypt', 'Ahmed Fatouh', -23, 'DF', 'placeholder_lineup_pending'),
  ('Egypt', 'Karim Hafez', 2656, 'DF', 'squad_missing_name_ok'),
  ('Egypt', 'Mohamed Hany', 2654, 'DF', 'fully_verified'),
  ('Egypt', 'Yasser Ibrahim', 16804, 'DF', 'fully_verified'),
  ('Egypt', 'Rami Rabia', 16805, 'DF', 'fully_verified'),
  ('Egypt', 'Emam Ashour', 17269, 'MF', 'fully_verified'),
  ('Egypt', 'Marwan Attia', 190575, 'MF', 'fully_verified'),
  ('Egypt', 'Nabil Emad', 2660, 'MF', 'squad_missing_name_ok'),
  ('Egypt', 'Hamdi Fathi', 16862, 'MF', 'squad_ok_name_suspect'),
  ('Egypt', 'Haitham Hassan', 20844, 'MF', 'squad_ok_name_suspect'),
  ('Egypt', 'Mohannad Lashin', -25, 'MF', 'placeholder_lineup_pending'),
  ('Egypt', 'Mahmoud Saber', 69196, 'MF', 'fully_verified'),
  ('Egypt', 'Mahmoud Hassan "Trezeguet"', 2664, 'MF', 'fully_verified'),
  ('Egypt', 'Mostafa Zico', 395075, 'MF', 'squad_missing_name_ok'),
  ('Egypt', 'Ahmed Sayed "Zizo"', 16871, 'MF', 'fully_verified'),
  ('Egypt', 'Hamza Abdulkarim', -24, 'FW', 'placeholder_lineup_pending'),
  ('Egypt', 'Ibrahim Adel', 70535, 'FW', 'fully_verified'),
  ('Egypt', 'Omar Marmoush', 81573, 'FW', 'fully_verified'),
  ('Egypt', 'Mohamed Salah', 306, 'FW', 'fully_verified'),
  ('Spain', 'Unai Simon', 47270, 'GK', 'fully_verified'),
  ('Spain', 'David Raya', 19465, 'GK', 'fully_verified'),
  ('Spain', 'Joan Garcia', -76, 'GK', 'placeholder_lineup_pending'),
  ('Spain', 'Pedro Porro', 47519, 'DF', 'fully_verified'),
  ('Spain', 'Marcos Llorente', 753, 'DF', 'fully_verified'),
  ('Spain', 'Aymeric Laporte', 622, 'DF', 'fully_verified'),
  ('Spain', 'Pau Cubarsi', 396623, 'DF', 'fully_verified'),
  ('Spain', 'Marc Pubill', -74, 'DF', 'placeholder_lineup_pending'),
  ('Spain', 'Eric Garcia', 182718, 'DF', 'fully_verified'),
  ('Spain', 'Marc Cucurella', 47380, 'DF', 'squad_ok_name_mismatch'),
  ('Spain', 'Alejandro Grimaldo', 563, 'DF', 'fully_verified'),
  ('Spain', 'Rodrigo Hernandez', 360159, 'MF', 'squad_missing_name_ok'),
  ('Spain', 'Martin Zubimendi', 47315, 'MF', 'fully_verified'),
  ('Spain', 'Pedri Gonzalez', 133609, 'MF', 'fully_verified'),
  ('Spain', 'Fabian Ruiz', 328, 'MF', 'club_match'),
  ('Spain', 'Mikel Merino', -73, 'MF', 'placeholder_lineup_pending'),
  ('Spain', 'Pablo Paez ''Gavi''', 1697, 'MF', 'squad_ok_name_mismatch'),
  ('Spain', 'Alex Baena', 182219, 'MF', 'fully_verified'),
  ('Spain', 'Mikel Oyarzabal', 47323, 'FW', 'squad_ok_name_mismatch'),
  ('Spain', 'Lamine Yamal', 386828, 'FW', 'fully_verified'),
  ('Spain', 'Ferran Torres', 931, 'FW', 'fully_verified'),
  ('Spain', 'Borja Iglesias', 47348, 'FW', 'fully_verified'),
  ('Spain', 'Dani Olmo', 1323, 'FW', 'fully_verified'),
  ('Spain', 'Victor Munoz', 338751, 'FW', 'fully_verified'),
  ('Spain', 'Nico Williams', 183799, 'FW', 'club_match'),
  ('Spain', 'Yeremy Pino', 184226, 'FW', 'fully_verified'),
  ('Uruguay', 'Santiago Mele', 61895, 'GK', 'fully_verified'),
  ('Uruguay', 'Fernando Muslera', 429, 'GK', 'squad_ok_name_suspect'),
  ('Uruguay', 'Sergio Rochet', 50077, 'GK', 'fully_verified'),
  ('Uruguay', 'Ronald Araújo', 101814, 'DF', 'fully_verified'),
  ('Uruguay', 'Santiago Bueno', 135334, 'DF', 'fully_verified'),
  ('Uruguay', 'Sebastián Cáceres', 51535, 'DF', 'fully_verified'),
  ('Uruguay', 'José María Giménez', 31, 'DF', 'fully_verified'),
  ('Uruguay', 'Mathías Olivera', 47254, 'DF', 'fully_verified'),
  ('Uruguay', 'Joaquín Piquerez', 51466, 'DF', 'fully_verified'),
  ('Uruguay', 'Guillermo Varela', 1290, 'DF', 'fully_verified'),
  ('Uruguay', 'Matías Viña', 51572, 'DF', 'fully_verified'),
  ('Uruguay', 'Maximiliano Araújo', 51776, 'MF', 'fully_verified'),
  ('Uruguay', 'Giorgian de Arrascaeta', 2612, 'MF', 'fully_verified'),
  ('Uruguay', 'Rodrigo Bentancur', 863, 'MF', 'squad_missing_name_ok'),
  ('Uruguay', 'Agustín Canobbio', 51603, 'MF', 'fully_verified'),
  ('Uruguay', 'Nicolás de la Cruz', 5995, 'MF', 'squad_ok_name_suspect'),
  ('Uruguay', 'Emiliano Martínez', 153083, 'MF', 'fully_verified'),
  ('Uruguay', 'Facundo Pellistri', 70078, 'MF', 'fully_verified'),
  ('Uruguay', 'Brian Rodríguez', 51618, 'MF', 'squad_ok_name_suspect'),
  ('Uruguay', 'Juan Manuel Sanabria', 162891, 'MF', 'fully_verified'),
  ('Uruguay', 'Manuel Ugarte', 51494, 'MF', 'fully_verified'),
  ('Uruguay', 'Federico Valverde', 756, 'MF', 'fully_verified'),
  ('Uruguay', 'Rodrigo Zalazar', 108563, 'MF', 'squad_missing_name_ok'),
  ('Uruguay', 'Rodrigo Aguirre', 16482, 'FW', 'fully_verified'),
  ('Uruguay', 'Federico Viñas', 51530, 'FW', 'fully_verified'),
  ('Uruguay', 'Darwin Núñez', 51617, 'FW', 'fully_verified'),
  ('Saudi Arabia', 'Ahmed Al Kassar', 44449, 'GK', 'fully_verified'),
  ('Saudi Arabia', 'Mohammed Al Owais', 44411, 'GK', 'fully_verified'),
  ('Saudi Arabia', 'Nawaf Al Aqidi', 193288, 'GK', 'fully_verified'),
  ('Saudi Arabia', 'Abdulqudus Attia', -47, 'GK', 'placeholder_lineup_pending'),
  ('Saudi Arabia', 'Saud Abdulhamid', 44594, 'DF', 'fully_verified'),
  ('Saudi Arabia', 'Mohammed Abu Al Shamat', -82, 'DF', 'placeholder_lineup_pending'),
  ('Saudi Arabia', 'Khalid Al Ghannam', 44701, 'DF', 'fully_verified'),
  ('Saudi Arabia', 'Moteb Al Harbi', 202381, 'DF', 'squad_missing_name_ok'),
  ('Saudi Arabia', 'Abdulelah Al Amri', 44475, 'DF', 'fully_verified'),
  ('Saudi Arabia', 'Nawaf Boushal', 134995, 'DF', 'fully_verified'),
  ('Saudi Arabia', 'Zakaria Hawsawi', 442343, 'DF', 'squad_ok_name_suspect'),
  ('Saudi Arabia', 'Hassan Kadesh', 44335, 'DF', 'fully_verified'),
  ('Saudi Arabia', 'Ali Lajami', 44507, 'DF', 'fully_verified'),
  ('Saudi Arabia', 'Ali Majrashi', 44367, 'DF', 'fully_verified'),
  ('Saudi Arabia', 'Hassan Tambakti', 44362, 'DF', 'fully_verified'),
  ('Saudi Arabia', 'Jehad Thikri', 304467, 'DF', 'squad_missing_name_flagged'),
  ('Saudi Arabia', 'Nasser Al Dawsari', 44339, 'MF', 'fully_verified'),
  ('Saudi Arabia', 'Alaa Al Hajji', -48, 'MF', 'placeholder_lineup_pending'),
  ('Saudi Arabia', 'Ziyad Al Johani', 269172, 'MF', 'fully_verified'),
  ('Saudi Arabia', 'Musab Al Juwayr', 306380, 'MF', 'fully_verified'),
  ('Saudi Arabia', 'Abdullah Al Khaibari', 44315, 'MF', 'fully_verified'),
  ('Saudi Arabia', 'Saleh Abu Al Shamat', 403087, 'MF', 'fully_verified'),
  ('Saudi Arabia', 'Mohammed Kanno', 44349, 'MF', 'squad_ok_name_suspect'),
  ('Saudi Arabia', 'Sultan Mandash', 2639, 'MF', 'fully_verified'),
  ('Saudi Arabia', 'Ayman Yahya', 147812, 'MF', 'fully_verified'),
  ('Saudi Arabia', 'Feras Al Brikan', 44324, 'FW', 'fully_verified'),
  ('Saudi Arabia', 'Salem Al Dawsari', -72, 'FW', 'placeholder_lineup_pending'),
  ('Saudi Arabia', 'Abdullah Al Hamdan', 44382, 'FW', 'fully_verified'),
  ('Saudi Arabia', 'Abdullah Al Salem', 44340, 'FW', 'fully_verified'),
  ('Saudi Arabia', 'Saleh Al Shehri', 44551, 'FW', 'fully_verified'),
  ('Cape Verde', 'Vozinha', 15304, 'GK', 'fully_verified'),
  ('Cape Verde', 'Marcio Rosa', 41764, 'GK', 'fully_verified'),
  ('Cape Verde', 'CJ dos Santos', 163200, 'GK', 'squad_ok_name_suspect'),
  ('Cape Verde', 'Diney Borges', 41608, 'DF', 'fully_verified'),
  ('Cape Verde', 'Sidny Cabral', 308689, 'DF', 'fully_verified'),
  ('Cape Verde', 'Logan Costa', 21997, 'DF', 'fully_verified'),
  ('Cape Verde', 'Steven Moreira', 22139, 'DF', 'fully_verified'),
  ('Cape Verde', 'Wagner Pina', 332056, 'DF', 'fully_verified'),
  ('Cape Verde', 'Joao Paulo Fernandes', 142016, 'DF', 'fully_verified'),
  ('Cape Verde', 'Roberto ''Pico'' Lopes', 69260, 'DF', 'fully_verified'),
  ('Cape Verde', 'Kelvin Pires', 268806, 'DF', 'fully_verified'),
  ('Cape Verde', 'Ianique ''Stopira'' Tavares', 2331, 'DF', 'fully_verified'),
  ('Cape Verde', 'Telmo Arcanjo', 265556, 'MF', 'fully_verified'),
  ('Cape Verde', 'Laros Duarte', 37436, 'MF', 'fully_verified'),
  ('Cape Verde', 'Deroy Duarte', 37435, 'MF', 'fully_verified'),
  ('Cape Verde', 'Jamiro Monteiro', 50745, 'MF', 'fully_verified'),
  ('Cape Verde', 'Kevin Pina', 96512, 'MF', 'fully_verified'),
  ('Cape Verde', 'Yannick Semedo', 128007, 'MF', 'fully_verified'),
  ('Cape Verde', 'Gilson Benchimol', 309182, 'FW', 'fully_verified'),
  ('Cape Verde', 'Jovane Cabral', 1494, 'FW', 'fully_verified'),
  ('Cape Verde', 'Nuno da Costa', 22265, 'FW', 'fully_verified'),
  ('Cape Verde', 'Dailon Livramento', 343287, 'FW', 'fully_verified'),
  ('Cape Verde', 'Ryan Mendes', 50270, 'FW', 'fully_verified'),
  ('Cape Verde', 'Garry Rodrigues', 44612, 'FW', 'fully_verified'),
  ('Cape Verde', 'Willy Semedo', 113580, 'FW', 'fully_verified'),
  ('Cape Verde', 'Helio Varela', 291024, 'FW', 'fully_verified'),
  ('France', 'Mike Maignan', 22221, 'GK', 'fully_verified'),
  ('France', 'Robin Risser', 347211, 'GK', 'fully_verified'),
  ('France', 'Brice Samba', 21628, 'GK', 'fully_verified'),
  ('France', 'Lucas Digne', 2724, 'DF', 'fully_verified'),
  ('France', 'Malo Gusto', 161907, 'DF', 'fully_verified'),
  ('France', 'Lucas Hernandez', 33, 'DF', 'fully_verified'),
  ('France', 'Theo Hernandez', 47300, 'DF', 'fully_verified'),
  ('France', 'Ibrahima Konate', 1145, 'DF', 'fully_verified'),
  ('France', 'Jules Kounde', 1257, 'DF', 'squad_missing_name_ok'),
  ('France', 'Maxence Lacroix', 20995, 'DF', 'fully_verified'),
  ('France', 'William Saliba', 22090, 'DF', 'squad_missing_name_ok'),
  ('France', 'Dayot Upamecano', 1149, 'DF', 'fully_verified'),
  ('France', 'N''Golo Kante', 2290, 'MF', 'fully_verified'),
  ('France', 'Manu Kone', 22147, 'MF', 'fully_verified'),
  ('France', 'Adrien Rabiot', 272, 'MF', 'fully_verified'),
  ('France', 'Aurelien Tchouameni', 1271, 'MF', 'fully_verified'),
  ('France', 'Warren Zaire-Emery', 336657, 'MF', 'fully_verified'),
  ('France', 'Maghnes Akliouche', 274300, 'FW', 'fully_verified'),
  ('France', 'Bradley Barcola', 161904, 'FW', 'squad_missing_name_ok'),
  ('France', 'Rayan Cherki', 156477, 'FW', 'fully_verified'),
  ('France', 'Ousmane Dembele', 153, 'FW', 'fully_verified'),
  ('France', 'Desire Doue', 343027, 'FW', 'fully_verified'),
  ('France', 'Jean-Philippe Mateta', 25927, 'FW', 'squad_missing_name_ok'),
  ('France', 'Kylian Mbappe', 278, 'FW', 'fully_verified'),
  ('France', 'Michael Olise', 19617, 'FW', 'fully_verified'),
  ('France', 'Marcus Thuram', 21509, 'FW', 'fully_verified'),
  ('Senegal', 'Mory Diaw', 119853, 'GK', 'fully_verified'),
  ('Senegal', 'Yehvann Diouf', 20566, 'GK', 'fully_verified'),
  ('Senegal', 'Edouard Mendy', 2986, 'GK', 'fully_verified'),
  ('Senegal', 'Ilay Camara', 371839, 'DF', 'fully_verified'),
  ('Senegal', 'Krepin Diatta', 81, 'DF', 'fully_verified'),
  ('Senegal', 'El Hadji Malick Diouf', 176541, 'DF', 'squad_missing_name_ok'),
  ('Senegal', 'Ismail Jakobs', 158121, 'DF', 'fully_verified'),
  ('Senegal', 'Kalidou Koulibaly', 318, 'DF', 'fully_verified'),
  ('Senegal', 'Moustapha Mbow', 408224, 'DF', 'squad_missing_name_flagged'),
  ('Senegal', 'Antoine Mendy', 313937, 'DF', 'fully_verified'),
  ('Senegal', 'Moussa Niakhate', 25916, 'DF', 'fully_verified'),
  ('Senegal', 'Mamadou Sarr', 276184, 'DF', 'fully_verified'),
  ('Senegal', 'Abdoulaye Seck', 8450, 'DF', 'fully_verified'),
  ('Senegal', 'Lamine Camara', 374058, 'MF', 'fully_verified'),
  ('Senegal', 'Pathe Ciss', 41552, 'MF', 'fully_verified'),
  ('Senegal', 'Habib Diarra', 327631, 'MF', 'fully_verified'),
  ('Senegal', 'Idrissa Gana Gueye', 2990, 'MF', 'fully_verified'),
  ('Senegal', 'Pape Gueye', 20696, 'MF', 'fully_verified'),
  ('Senegal', 'Pape Matar Sarr', 237129, 'MF', 'fully_verified'),
  ('Senegal', 'Bara Sapoko Ndiaye', -70, 'MF', 'placeholder_lineup_pending'),
  ('Senegal', 'Assane Diao', 400948, 'FW', 'fully_verified'),
  ('Senegal', 'Bamba Dieng', 284072, 'FW', 'fully_verified'),
  ('Senegal', 'Nicolas Jackson', 283058, 'FW', 'fully_verified'),
  ('Senegal', 'Sadio Mane', 304, 'FW', 'fully_verified'),
  ('Senegal', 'Ibrahim Mbaye', 446249, 'FW', 'fully_verified'),
  ('Senegal', 'Cherif Ndiaye', 14379, 'FW', 'squad_ok_name_suspect'),
  ('Senegal', 'Iliman Ndiaye', 18592, 'FW', 'fully_verified'),
  ('Senegal', 'Ismaila Sarr', 2218, 'FW', 'fully_verified'),
  ('Norway', 'Orjan Haskjold Nyland', 19172, 'GK', 'squad_ok_name_suspect'),
  ('Norway', 'Egil Selvik', 39082, 'GK', 'fully_verified'),
  ('Norway', 'Sander Tangvik', 264378, 'GK', 'squad_missing_name_ok'),
  ('Norway', 'Kristoffer Vassbakk Ajer', 1119, 'DF', 'fully_verified'),
  ('Norway', 'Fredrik Bjorkan', 39058, 'DF', 'club_match'),
  ('Norway', 'Henrik Falchener', 180937, 'DF', 'fully_verified'),
  ('Norway', 'Sondre Langas', 265444, 'DF', 'squad_missing_name_ok'),
  ('Norway', 'Torbjorn Heggem', 39254, 'DF', 'fully_verified'),
  ('Norway', 'Marcus Holmgren Pedersen', 39362, 'DF', 'fully_verified'),
  ('Norway', 'Julian Ryerson', 24845, 'DF', 'fully_verified'),
  ('Norway', 'David Moller Wolfe', 265782, 'DF', 'fully_verified'),
  ('Norway', 'Leo Ostigard', 18967, 'DF', 'club_match'),
  ('Norway', 'Thelonious Aasgaard', 277930, 'MF', 'squad_missing_name_ok'),
  ('Norway', 'Fredrik Aursnes', 39043, 'MF', 'squad_missing_name_ok'),
  ('Norway', 'Patrick Berg', 39064, 'MF', 'fully_verified'),
  ('Norway', 'Sander Berge', 1934, 'MF', 'fully_verified'),
  ('Norway', 'Oscar Bobb', 278133, 'MF', 'fully_verified'),
  ('Norway', 'Jens Petter Hauge', 39073, 'MF', 'fully_verified'),
  ('Norway', 'Antonio Nusa', 314511, 'MF', 'fully_verified'),
  ('Norway', 'Andreas Schjelderup', 301528, 'MF', 'fully_verified'),
  ('Norway', 'Morten Thorsby', 36980, 'MF', 'fully_verified'),
  ('Norway', 'Kristian Thorstvedt', 39143, 'MF', 'fully_verified'),
  ('Norway', 'Martin Odegaard', 37127, 'MF', 'club_match'),
  ('Norway', 'Erling Haaland', 1100, 'FW', 'fully_verified'),
  ('Norway', 'Jorgen Strand Larsen', 2032, 'FW', 'squad_ok_name_suspect'),
  ('Norway', 'Alexander Sorloth', 8492, 'FW', 'club_match'),
  ('Iraq', 'Ahmed Basil', 197933, 'GK', 'fully_verified'),
  ('Iraq', 'Jalal Hassan', 53886, 'GK', 'squad_missing_name_ok'),
  ('Iraq', 'Fahad Talib', 123802, 'GK', 'fully_verified'),
  ('Iraq', 'Hussein Ali', -75, 'DF', 'placeholder_lineup_pending'),
  ('Iraq', 'Merchas Doski', 271444, 'DF', 'fully_verified'),
  ('Iraq', 'Akam Hashem', 453073, 'DF', 'squad_ok_name_mismatch'),
  ('Iraq', 'Frans Putros', 15769, 'DF', 'fully_verified'),
  ('Iraq', 'Mustafa Saadoon', -33, 'DF', 'placeholder_lineup_pending'),
  ('Iraq', 'Rebin Sulaka', 42261, 'DF', 'squad_ok_name_mismatch'),
  ('Iraq', 'Zaid Tahseen', 296373, 'DF', 'squad_ok_name_suspect'),
  ('Iraq', 'Ahmed Yahya', 345750, 'DF', 'squad_missing_name_ok'),
  ('Iraq', 'Manaf Younis', -32, 'DF', 'placeholder_lineup_pending'),
  ('Iraq', 'Amir Al Ammari', 47792, 'MF', 'fully_verified'),
  ('Iraq', 'Youssef Amyn', 282065, 'MF', 'fully_verified'),
  ('Iraq', 'Ibrahim Bayesh', 140747, 'MF', 'squad_ok_name_suspect'),
  ('Iraq', 'Marko Farji', 265448, 'MF', 'fully_verified'),
  ('Iraq', 'Zidane Iqbal', 284295, 'MF', 'fully_verified'),
  ('Iraq', 'Zaid Ismail', 72131, 'MF', 'squad_missing_name_flagged'),
  ('Iraq', 'Ali Jassim', -80, 'MF', 'placeholder_lineup_pending'),
  ('Iraq', 'Ahmed Qasim', 395628, 'MF', 'squad_missing_name_flagged'),
  ('Iraq', 'Aimar Sher', 48129, 'MF', 'fully_verified'),
  ('Iraq', 'Kevin Yakob', 48025, 'MF', 'fully_verified'),
  ('Iraq', 'Mohanad Ali', 145465, 'FW', 'fully_verified'),
  ('Iraq', 'Aymen Hussein', 49451, 'FW', 'fully_verified'),
  ('Iraq', 'Ali Al Hamadi', 299813, 'FW', 'squad_ok_name_mismatch'),
  ('Iraq', 'Ali Yousef', -79, 'FW', 'placeholder_lineup_pending'),
  ('Argentina', 'Emiliano Martínez', 19599, 'GK', 'fully_verified'),
  ('Argentina', 'Geronimo Rulli', 47296, 'GK', 'fully_verified'),
  ('Argentina', 'Juan Musso', 2465, 'GK', 'fully_verified'),
  ('Argentina', 'Nahuel Molina', 6503, 'DF', 'fully_verified'),
  ('Argentina', 'Gonzalo Montiel', 2468, 'DF', 'squad_missing_name_ok'),
  ('Argentina', 'Cristian Romero', 30776, 'DF', 'fully_verified'),
  ('Argentina', 'Leonardo Balerdi', 6, 'DF', 'squad_missing_name_ok'),
  ('Argentina', 'Nicolas Otamendi', 624, 'DF', 'fully_verified'),
  ('Argentina', 'Lisandro Martinez', -69, 'DF', 'placeholder_lineup_pending'),
  ('Argentina', 'Nicolas Tagliafico', 529, 'DF', 'fully_verified'),
  ('Argentina', 'Facundo Medina', 6231, 'DF', 'squad_missing_name_ok'),
  ('Argentina', 'Leandro Paredes', 271, 'MF', 'fully_verified'),
  ('Argentina', 'Alexis Mac Allister', 6716, 'MF', 'fully_verified'),
  ('Argentina', 'Rodrigo De Paul', 2472, 'MF', 'fully_verified'),
  ('Argentina', 'Giovani Lo Celso', 1578, 'MF', 'squad_missing_name_ok'),
  ('Argentina', 'Exequiel Palacios', 6002, 'MF', 'fully_verified'),
  ('Argentina', 'Enzo Fernandez', 5996, 'MF', 'fully_verified'),
  ('Argentina', 'Valentin Barco', 319572, 'MF', 'fully_verified'),
  ('Argentina', 'Lionel Messi', 154, 'FW', 'fully_verified'),
  ('Argentina', 'Julian Alvarez', 6009, 'FW', 'fully_verified'),
  ('Argentina', 'Lautaro Martinez', 6000, 'FW', 'squad_ok_name_suspect'),
  ('Argentina', 'Thiago Almada', 6067, 'FW', 'fully_verified'),
  ('Argentina', 'Nicolas Paz', 350037, 'FW', 'fully_verified'),
  ('Argentina', 'Nicolas Gonzalez', 26315, 'FW', 'fully_verified'),
  ('Argentina', 'Giuliano Simeone', 323935, 'FW', 'fully_verified'),
  ('Argentina', 'Jose Manuel Lopez', 295513, 'FW', 'fully_verified'),
  ('Austria', 'Patrick Pentz', 7598, 'GK', 'fully_verified'),
  ('Austria', 'Alexander Schlager', 7525, 'GK', 'fully_verified'),
  ('Austria', 'Florian Wiegele', 221605, 'GK', 'fully_verified'),
  ('Austria', 'David Affengruber', 126640, 'DF', 'fully_verified'),
  ('Austria', 'David Alaba', 505, 'DF', 'fully_verified'),
  ('Austria', 'Kevin Danso', 25287, 'DF', 'fully_verified'),
  ('Austria', 'Marco Friedl', 25314, 'DF', 'fully_verified'),
  ('Austria', 'Philipp Lienhart', 26240, 'DF', 'fully_verified'),
  ('Austria', 'Phillipp Mwene', 25915, 'DF', 'fully_verified'),
  ('Austria', 'Stefan Posch', 711, 'DF', 'fully_verified'),
  ('Austria', 'Alexander Prass', 7327, 'DF', 'fully_verified'),
  ('Austria', 'Michael Svoboda', 7090, 'DF', 'fully_verified'),
  ('Austria', 'Christoph Baumgartner', 715, 'MF', 'fully_verified'),
  ('Austria', 'Carney Chukwuemeka', 138935, 'MF', 'fully_verified'),
  ('Austria', 'Florian Grillitsch', 719, 'MF', 'fully_verified'),
  ('Austria', 'Konrad Laimer', 1157, 'MF', 'fully_verified'),
  ('Austria', 'Marcel Sabitzer', 1159, 'MF', 'fully_verified'),
  ('Austria', 'Xaver Schlager', 1095, 'MF', 'fully_verified'),
  ('Austria', 'Romano Schmid', 7562, 'MF', 'fully_verified'),
  ('Austria', 'Alessandro Schopf', 417, 'MF', 'squad_missing_name_ok'),
  ('Austria', 'Nicolas Seiwald', 7328, 'MF', 'fully_verified'),
  ('Austria', 'Paul Wanner', 327895, 'MF', 'fully_verified'),
  ('Austria', 'Patrick Wimmer', 126642, 'MF', 'fully_verified'),
  ('Austria', 'Marko Arnautovic', 18830, 'FW', 'fully_verified'),
  ('Austria', 'Michael Gregoritsch', 25297, 'FW', 'fully_verified'),
  ('Austria', 'Sasa Kalajdzic', 7722, 'FW', 'fully_verified'),
  ('Algeria', 'Oussama Benbot', 4414, 'GK', 'squad_missing_name_ok'),
  ('Algeria', 'Melvin Mastil', 304229, 'GK', 'fully_verified'),
  ('Algeria', 'Luca Zidane', 732, 'GK', 'fully_verified'),
  ('Algeria', 'Achref Abada', 342740, 'DF', 'fully_verified'),
  ('Algeria', 'Rayan Aït-Nouri', 21138, 'DF', 'fully_verified'),
  ('Algeria', 'Zineddine Belaïd', 4561, 'DF', 'fully_verified'),
  ('Algeria', 'Rafik Belghali', 303362, 'DF', 'fully_verified'),
  ('Algeria', 'Ramy Bensebaïni', 2194, 'DF', 'squad_ok_name_suspect'),
  ('Algeria', 'Samir Sophian Chergui', 20869, 'DF', 'squad_missing_name_ok'),
  ('Algeria', 'Jaouen Hadjam', 271539, 'DF', 'squad_missing_name_ok'),
  ('Algeria', 'Aïssa Mandi', 1567, 'DF', 'fully_verified'),
  ('Algeria', 'Mohamed Tougai', 4569, 'DF', 'squad_missing_name_ok'),
  ('Algeria', 'Houssem Aouar', 658, 'MF', 'fully_verified'),
  ('Algeria', 'Nabil Bentaleb', 409, 'MF', 'squad_missing_name_ok'),
  ('Algeria', 'Hicham Boudaoui', 4399, 'MF', 'fully_verified'),
  ('Algeria', 'Farès Chaïbi', 276670, 'MF', 'fully_verified'),
  ('Algeria', 'Ibrahim Maza', 380587, 'MF', 'fully_verified'),
  ('Algeria', 'Yacine Titraoui', 327599, 'MF', 'fully_verified'),
  ('Algeria', 'Ramiz Zerrouki', 129047, 'MF', 'fully_verified'),
  ('Algeria', 'Mohamed Amoura', 200139, 'FW', 'fully_verified'),
  ('Algeria', 'Nadhir Benbouali', 292924, 'FW', 'fully_verified'),
  ('Algeria', 'Adil Boulbina', 329163, 'FW', 'fully_verified'),
  ('Algeria', 'Farès Ghedjemis', 334915, 'FW', 'fully_verified'),
  ('Algeria', 'Amine Gouiri', 85041, 'FW', 'fully_verified'),
  ('Algeria', 'Riyad Mahrez', 635, 'FW', 'fully_verified'),
  ('Algeria', 'Anis Hadj Moussa', 326067, 'FW', 'fully_verified'),
  ('Jordan', 'Yazid Abulaila', 140607, 'GK', 'squad_ok_name_mismatch'),
  ('Jordan', 'Abdallah Al Fakhouri', 163884, 'GK', 'fully_verified'),
  ('Jordan', 'Ahmad Al Juaidi', 213985, 'GK', 'squad_missing_name_ok'),
  ('Jordan', 'Nour Bani Attiah', -38, 'GK', 'placeholder_lineup_pending'),
  ('Jordan', 'Mohammad Abualnadi', 102538, 'DF', 'fully_verified'),
  ('Jordan', 'Yousef Abu Al Jazar', 140608, 'DF', 'fully_verified'),
  ('Jordan', 'Husam Abu Dahab', 542822, 'DF', 'fully_verified'),
  ('Jordan', 'Mohammad Abu Hashish', -36, 'DF', 'placeholder_lineup_pending'),
  ('Jordan', 'Mohannad Abu Taha', -81, 'DF', 'placeholder_lineup_pending'),
  ('Jordan', 'Yazan Al Arab', 53900, 'DF', 'fully_verified'),
  ('Jordan', 'Saed Al Rosan', 213978, 'DF', 'fully_verified'),
  ('Jordan', 'Ahmad Assaf', 542855, 'DF', 'fully_verified'),
  ('Jordan', 'Anas Badawi', -35, 'DF', 'placeholder_lineup_pending'),
  ('Jordan', 'Abdallah Nasib', -34, 'DF', 'placeholder_lineup_pending'),
  ('Jordan', 'Ehsan Haddad', 53902, 'DF', 'squad_missing_name_ok'),
  ('Jordan', 'Saleem Obaid', 72140, 'DF', 'fully_verified'),
  ('Jordan', 'Mohammad Taha', 310785, 'DF', 'fully_verified'),
  ('Jordan', 'Mohammad Al Dawoud', -37, 'MF', 'placeholder_lineup_pending'),
  ('Jordan', 'Nizar Al Rashdan', 213980, 'MF', 'fully_verified'),
  ('Jordan', 'Noor Al Rawabdeh', 140609, 'MF', 'fully_verified'),
  ('Jordan', 'Rajaei Ayed', 104242, 'MF', 'fully_verified'),
  ('Jordan', 'Amer Jamous', 198211, 'MF', 'fully_verified'),
  ('Jordan', 'Yousef Qashi', 618026, 'MF', 'fully_verified'),
  ('Jordan', 'Ibrahim Sadeh', 542768, 'MF', 'fully_verified'),
  ('Jordan', 'Mohammad Abu Zraiq', 393152, 'FW', 'squad_missing_name_ok'),
  ('Jordan', 'Mousa Al Tamari', 15286, 'FW', 'fully_verified'),
  ('Jordan', 'Ali Azaizeh', 575283, 'FW', 'fully_verified'),
  ('Jordan', 'Odeh Fakhoury', -39, 'FW', 'placeholder_lineup_pending'),
  ('Jordan', 'Ali Olwan', 164026, 'FW', 'fully_verified'),
  ('Jordan', 'Ibrahim Sabra', 432841, 'FW', 'fully_verified'),
  ('Portugal', 'Diogo Costa', -77, 'GK', 'placeholder_lineup_pending'),
  ('Portugal', 'Jose Sa', 1590, 'GK', 'fully_verified'),
  ('Portugal', 'Rui Silva', 46672, 'GK', 'fully_verified'),
  ('Portugal', 'Ricardo Velho', 41960, 'GK', 'fully_verified'),
  ('Portugal', 'Tomas Araujo', 161939, 'DF', 'fully_verified'),
  ('Portugal', 'Joao Cancelo', 855, 'DF', 'fully_verified'),
  ('Portugal', 'Diogo Dalot', 886, 'DF', 'fully_verified'),
  ('Portugal', 'Ruben Dias', -67, 'DF', 'placeholder_lineup_pending'),
  ('Portugal', 'Goncalo Inacio', 265595, 'DF', 'fully_verified'),
  ('Portugal', 'Nuno Mendes', 263482, 'DF', 'fully_verified'),
  ('Portugal', 'Matheus Nunes', 41621, 'DF', 'fully_verified'),
  ('Portugal', 'Nelson Semedo', 96364, 'DF', 'squad_missing_name_ok'),
  ('Portugal', 'Renato Veiga', 336671, 'DF', 'fully_verified'),
  ('Portugal', 'Samuel Costa', 190485, 'MF', 'squad_ok_name_suspect'),
  ('Portugal', 'Bruno Fernandes', 1485, 'MF', 'fully_verified'),
  ('Portugal', 'Joao Neves', 335051, 'MF', 'fully_verified'),
  ('Portugal', 'Ruben Neves', 2676, 'MF', 'squad_ok_name_mismatch'),
  ('Portugal', 'Bernardo Silva', 119612, 'MF', 'squad_missing_name_ok'),
  ('Portugal', 'Vitinha', 128384, 'MF', 'fully_verified'),
  ('Portugal', 'Francisco Conceicao', 161585, 'FW', 'fully_verified'),
  ('Portugal', 'Joao Felix', 583, 'FW', 'fully_verified'),
  ('Portugal', 'Goncalo Guedes', 925, 'FW', 'fully_verified'),
  ('Portugal', 'Rafael Leao', 22236, 'FW', 'squad_missing_name_ok'),
  ('Portugal', 'Pedro Neto', 1864, 'FW', 'fully_verified'),
  ('Portugal', 'Goncalo Ramos', 41585, 'FW', 'fully_verified'),
  ('Portugal', 'Cristiano Ronaldo', 874, 'FW', 'squad_missing_name_ok'),
  ('Portugal', 'Francisco Trincao', 41112, 'FW', 'fully_verified'),
  ('Colombia', 'Alvaro Montero', 2481, 'GK', 'fully_verified'),
  ('Colombia', 'Camilo Vargas', 2482, 'GK', 'fully_verified'),
  ('Colombia', 'David Ospina', 313, 'GK', 'fully_verified'),
  ('Colombia', 'Daniel Munoz', 13736, 'DF', 'fully_verified'),
  ('Colombia', 'Santiago Arias', 30, 'DF', 'fully_verified'),
  ('Colombia', 'Davinson Sanchez', 168, 'DF', 'fully_verified'),
  ('Colombia', 'Jhon Lucumi', 1929, 'DF', 'fully_verified'),
  ('Colombia', 'Yerry Mina', 2484, 'DF', 'fully_verified'),
  ('Colombia', 'Willer Ditta', 13571, 'DF', 'squad_missing_name_ok'),
  ('Colombia', 'Deiver Machado', 2483, 'DF', 'fully_verified'),
  ('Colombia', 'Johan Mojica', 64268, 'DF', 'fully_verified'),
  ('Colombia', 'Gustavo Puerta', 324034, 'MF', 'fully_verified'),
  ('Colombia', 'James Rodriguez', 517, 'MF', 'fully_verified'),
  ('Colombia', 'Jefferson Lerma', 2490, 'MF', 'fully_verified'),
  ('Colombia', 'Jhon Arias', 13708, 'MF', 'fully_verified'),
  ('Colombia', 'Jorge Carrascal', 5994, 'MF', 'fully_verified'),
  ('Colombia', 'Juan Fernando Quintero', 6005, 'MF', 'fully_verified'),
  ('Colombia', 'Richard Rios', 195104, 'MF', 'fully_verified'),
  ('Colombia', 'Kevin Castano', 289592, 'MF', 'fully_verified'),
  ('Colombia', 'Jaminton Campaz', 13376, 'MF', 'fully_verified'),
  ('Colombia', 'Juan Portilla', 13151, 'MF', 'squad_missing_name_ok'),
  ('Colombia', 'Luis Diaz', 2489, 'FW', 'fully_verified'),
  ('Colombia', 'Luis Suarez', 47237, 'FW', 'fully_verified'),
  ('Colombia', 'Jhon Cordoba', 24810, 'FW', 'fully_verified'),
  ('Colombia', 'Carlos Gomez', 345748, 'FW', 'fully_verified'),
  ('Colombia', 'Juan Camilo Hernandez', 47582, 'FW', 'squad_missing_name_ok'),
  ('DR Congo', 'Lionel Mpasi', 24012, 'GK', 'fully_verified'),
  ('DR Congo', 'Thimothy Fayulu', 48501, 'GK', 'squad_ok_name_suspect'),
  ('DR Congo', 'Matthieu Epolo', 314509, 'GK', 'fully_verified'),
  ('DR Congo', 'Chancel Mbemba', 375, 'DF', 'fully_verified'),
  ('DR Congo', 'Aaron Wan-Bissaka', 18846, 'DF', 'fully_verified'),
  ('DR Congo', 'Alex Tuanzebe', 19182, 'DF', 'squad_ok_name_suspect'),
  ('DR Congo', 'Arthur Masuaku', 18816, 'DF', 'fully_verified'),
  ('DR Congo', 'Joris Kayembe', 21098, 'DF', 'fully_verified'),
  ('DR Congo', 'Steve Kapuadi', 199767, 'DF', 'fully_verified'),
  ('DR Congo', 'Aaron Tshibola', 44791, 'DF', 'squad_missing_name_ok'),
  ('DR Congo', 'Dylan Batubinsika', 8445, 'DF', 'fully_verified'),
  ('DR Congo', 'Gédéon Kalulu', 24245, 'DF', 'fully_verified'),
  ('DR Congo', 'Noah Sadiki', 365331, 'MF', 'fully_verified'),
  ('DR Congo', 'Samuel Moutoussamy', 21101, 'MF', 'fully_verified'),
  ('DR Congo', 'Edo Kayembe', 1424, 'MF', 'fully_verified'),
  ('DR Congo', 'Ngal''ayel Mukau', 375598, 'MF', 'fully_verified'),
  ('DR Congo', 'Charles Pickel', 48555, 'MF', 'fully_verified'),
  ('DR Congo', 'Nathanael Mbuku', 129670, 'MF', 'fully_verified'),
  ('DR Congo', 'Brian Cipenga', 279482, 'MF', 'fully_verified'),
  ('DR Congo', 'Meschack Elia', 3034, 'MF', 'fully_verified'),
  ('DR Congo', 'Gael Kakuta', 47545, 'MF', 'fully_verified'),
  ('DR Congo', 'Theo Bongonda', 8627, 'FW', 'fully_verified'),
  ('DR Congo', 'Fiston Mayele', 179699, 'FW', 'fully_verified'),
  ('DR Congo', 'Cedric Bakambu', 3033, 'FW', 'fully_verified'),
  ('DR Congo', 'Simon Banza', 20674, 'FW', 'fully_verified'),
  ('DR Congo', 'Yoane Wissa', 20649, 'FW', 'fully_verified'),
  ('Uzbekistan', 'Botirali Ergashev', 72120, 'GK', 'fully_verified'),
  ('Uzbekistan', 'Abduvohid Nematov', -59, 'GK', 'placeholder_lineup_pending'),
  ('Uzbekistan', 'Utkir Yusupov', 73534, 'GK', 'fully_verified'),
  ('Uzbekistan', 'Abdullah Abdullaev', -58, 'DF', 'placeholder_lineup_pending'),
  ('Uzbekistan', 'Khojiakbar Alijonov', 72122, 'DF', 'fully_verified'),
  ('Uzbekistan', 'Rustamjon Ashurmatov', 34121, 'DF', 'fully_verified'),
  ('Uzbekistan', 'Umarbek Eshmuradov', -65, 'DF', 'placeholder_lineup_pending'),
  ('Uzbekistan', 'Bekhruz Karimov', 416964, 'DF', 'squad_ok_name_suspect'),
  ('Uzbekistan', 'Abdukodir Khusanov', 360114, 'DF', 'squad_ok_name_suspect'),
  ('Uzbekistan', 'Sherzod Nasrullaev', -63, 'DF', 'placeholder_lineup_pending'),
  ('Uzbekistan', 'Umaraali Rakhmonaliev', -64, 'DF', 'placeholder_lineup_pending'),
  ('Uzbekistan', 'Farrukh Sayfiev', 532759, 'DF', 'fully_verified'),
  ('Uzbekistan', 'Avazbek Ulmasaliev', 65571, 'DF', 'squad_missing_name_ok'),
  ('Uzbekistan', 'Jakhongir Urozov', 358427, 'DF', 'fully_verified'),
  ('Uzbekistan', 'Ruslanbek Yiyanov', 312231, 'DF', 'squad_missing_name_flagged'),
  ('Uzbekistan', 'Sherzod Esanov', 363723, 'MF', 'squad_missing_name_ok'),
  ('Uzbekistan', 'Azizbek Ganiev', -60, 'MF', 'placeholder_lineup_pending'),
  ('Uzbekistan', 'Dostonbek Hamdamov', 53834, 'MF', 'lookup_match'),
  ('Uzbekistan', 'Odiljon Hamrobekov', 53835, 'MF', 'fully_verified'),
  ('Uzbekistan', 'Jamshid Iskanderov', 65576, 'MF', 'fully_verified'),
  ('Uzbekistan', 'Jashur Jaloliddinov', -61, 'MF', 'placeholder_lineup_pending'),
  ('Uzbekistan', 'Akmal Mozgovoy', 73522, 'MF', 'fully_verified'),
  ('Uzbekistan', 'Otabek Shukurov', 50272, 'MF', 'fully_verified'),
  ('Uzbekistan', 'Azizbek Amonov', 65584, 'FW', 'squad_missing_name_ok'),
  ('Uzbekistan', 'Abbosbek Fayzullaev', 263676, 'FW', 'squad_missing_name_ok'),
  ('Uzbekistan', 'Jaloliddin Masharipov', 53836, 'FW', 'squad_missing_name_ok'),
  ('Uzbekistan', 'Eldor Shomurodov', 53535, 'FW', 'fully_verified'),
  ('Uzbekistan', 'Igor Sergeev', 72128, 'FW', 'fully_verified'),
  ('Uzbekistan', 'Sherzod Temirov', 546505, 'FW', 'fully_verified'),
  ('Uzbekistan', 'Oston Urunov', -62, 'FW', 'placeholder_lineup_pending'),
  ('England', 'Dean Henderson', 19088, 'GK', 'fully_verified'),
  ('England', 'Jordan Pickford', 2932, 'GK', 'fully_verified'),
  ('England', 'James Trafford', 162489, 'GK', 'fully_verified'),
  ('England', 'Dan Burn', 18961, 'DF', 'fully_verified'),
  ('England', 'Marc Guehi', 67971, 'DF', 'fully_verified'),
  ('England', 'Reece James', 19545, 'DF', 'fully_verified'),
  ('England', 'Ezri Konsa', 19354, 'DF', 'fully_verified'),
  ('England', 'Tino Livramento', 158694, 'DF', 'fully_verified'),
  ('England', 'Nico O''Reilly', 307123, 'DF', 'club_match'),
  ('England', 'Jarell Quansah', 158698, 'DF', 'fully_verified'),
  ('England', 'Djed Spence', 19235, 'DF', 'fully_verified'),
  ('England', 'John Stones', 626, 'DF', 'fully_verified'),
  ('England', 'Elliott Anderson', 138908, 'MF', 'fully_verified'),
  ('England', 'Jude Bellingham', 129718, 'MF', 'fully_verified'),
  ('England', 'Eberechi Eze', 19586, 'MF', 'fully_verified'),
  ('England', 'Jordan Henderson', 292, 'MF', 'fully_verified'),
  ('England', 'Kobbie Mainoo', 284322, 'MF', 'fully_verified'),
  ('England', 'Declan Rice', 2937, 'MF', 'fully_verified'),
  ('England', 'Morgan Rogers', 19170, 'MF', 'fully_verified'),
  ('England', 'Anthony Gordon', 138787, 'FW', 'fully_verified'),
  ('England', 'Harry Kane', 184, 'FW', 'fully_verified'),
  ('England', 'Noni Madueke', 136723, 'FW', 'squad_ok_name_suspect'),
  ('England', 'Marcus Rashford', 909, 'FW', 'fully_verified'),
  ('England', 'Bukayo Saka', 1460, 'FW', 'fully_verified'),
  ('England', 'Ivan Toney', 19974, 'FW', 'fully_verified'),
  ('England', 'Ollie Watkins', 19366, 'FW', 'squad_ok_name_suspect'),
  ('Croatia', 'Dominik Livakovic', 1305, 'GK', 'fully_verified'),
  ('Croatia', 'Dominik Kotarski', 524, 'GK', 'fully_verified'),
  ('Croatia', 'Ivor Pandur', 14268, 'GK', 'fully_verified'),
  ('Croatia', 'Josko Gvardiol', 129033, 'DF', 'fully_verified'),
  ('Croatia', 'Duje Caleta-Car', 1902, 'DF', 'fully_verified'),
  ('Croatia', 'Josip Sutalo', 14701, 'DF', 'fully_verified'),
  ('Croatia', 'Josip Stanisic', 125171, 'DF', 'fully_verified'),
  ('Croatia', 'Marin Pongracic', 1084, 'DF', 'fully_verified'),
  ('Croatia', 'Martin Erlic', 30827, 'DF', 'fully_verified'),
  ('Croatia', 'Luka Vuskovic', 387521, 'DF', 'fully_verified'),
  ('Croatia', 'Luka Modric', 754, 'MF', 'fully_verified'),
  ('Croatia', 'Mateo Kovacic', 2291, 'MF', 'fully_verified'),
  ('Croatia', 'Mario Pasalic', -78, 'MF', 'placeholder_lineup_pending'),
  ('Croatia', 'Nikola Vlasic', 842, 'MF', 'fully_verified'),
  ('Croatia', 'Luka Sucic', 7332, 'MF', 'fully_verified'),
  ('Croatia', 'Martin Baturina', 295026, 'MF', 'fully_verified'),
  ('Croatia', 'Kristijan Jakic', 14395, 'MF', 'fully_verified'),
  ('Croatia', 'Petar Sucic', 348205, 'MF', 'fully_verified'),
  ('Croatia', 'Nikola Moro', 1322, 'MF', 'fully_verified'),
  ('Croatia', 'Toni Fruk', 284869, 'MF', 'fully_verified'),
  ('Croatia', 'Ivan Perisic', 207, 'FW', 'fully_verified'),
  ('Croatia', 'Andrej Kramaric', 726, 'FW', 'fully_verified'),
  ('Croatia', 'Ante Budimir', 46746, 'FW', 'fully_verified'),
  ('Croatia', 'Marco Pasalic', 260865, 'FW', 'squad_ok_name_suspect'),
  ('Croatia', 'Petar Musa', 66055, 'FW', 'fully_verified'),
  ('Croatia', 'Igor Matanovic', 202696, 'FW', 'fully_verified'),
  ('Ghana', 'Lawrence Ati-Zigi', -27, 'GK', 'placeholder_lineup_pending'),
  ('Ghana', 'Benjamin Asare', 480108, 'GK', 'squad_missing_name_ok'),
  ('Ghana', 'Joseph Anang', 144709, 'GK', 'fully_verified'),
  ('Ghana', 'Jonas Adjetey', 369425, 'DF', 'fully_verified'),
  ('Ghana', 'Baba Abdul Rahman', 21996, 'DF', 'squad_missing_name_ok'),
  ('Ghana', 'Gideon Mensah', 7578, 'DF', 'fully_verified'),
  ('Ghana', 'Abdul Mumin', 15900, 'DF', 'squad_missing_name_ok'),
  ('Ghana', 'Jerome Opoku', 137223, 'DF', 'fully_verified'),
  ('Ghana', 'Kojo Oppong Peprah', 404172, 'DF', 'fully_verified'),
  ('Ghana', 'Alidu Seidu', 196187, 'DF', 'squad_missing_name_ok'),
  ('Ghana', 'Marvin Senaya', 191240, 'DF', 'fully_verified'),
  ('Ghana', 'Augustine Boakye', 337426, 'MF', 'squad_missing_name_ok'),
  ('Ghana', 'Abdul Fatawu', 303467, 'MF', 'fully_verified'),
  ('Ghana', 'Elisha Owusu', 21010, 'MF', 'fully_verified'),
  ('Ghana', 'Thomas Partey', 49, 'MF', 'fully_verified'),
  ('Ghana', 'Kwasi Sibo', 3608, 'MF', 'fully_verified'),
  ('Ghana', 'Kamaldeen Sulemana', 199837, 'MF', 'fully_verified'),
  ('Ghana', 'Caleb Yirenkyi', 475575, 'MF', 'fully_verified'),
  ('Ghana', 'Jordan Ayew', 3428, 'FW', 'fully_verified'),
  ('Ghana', 'Christopher Bonsu Baah', 411800, 'FW', 'fully_verified'),
  ('Ghana', 'Prince Kwabena Adu', 410016, 'FW', 'fully_verified'),
  ('Ghana', 'Ernest Nuamah', 350856, 'FW', 'squad_missing_name_ok'),
  ('Ghana', 'Antoine Semenyo', 19281, 'FW', 'fully_verified'),
  ('Ghana', 'Brandon Thomas-Asante', -26, 'FW', 'placeholder_lineup_pending'),
  ('Ghana', 'Inaki Williams', 47294, 'FW', 'club_match'),
  ('Ghana', 'Derrick Luckassen', 25341, 'DF', 'lookup_match'),
  ('Panama', 'Orlando Mosquera', 2968, 'GK', 'fully_verified'),
  ('Panama', 'Luis Mejia', 2967, 'GK', 'fully_verified'),
  ('Panama', 'Cesar Samudio', 57861, 'GK', 'fully_verified'),
  ('Panama', 'Cesar Blackman', 2975, 'DF', 'fully_verified'),
  ('Panama', 'Jorge Gutierrez', 57803, 'DF', 'fully_verified'),
  ('Panama', 'Amir Murillo', 2973, 'DF', 'fully_verified'),
  ('Panama', 'Fidel Escobar', 2971, 'DF', 'squad_missing_name_ok'),
  ('Panama', 'Andres Andrade', 7197, 'DF', 'fully_verified'),
  ('Panama', 'Edgardo Farina', 328148, 'DF', 'fully_verified'),
  ('Panama', 'Jose Cordoba', 57739, 'DF', 'fully_verified'),
  ('Panama', 'Eric Davis', 2970, 'DF', 'fully_verified'),
  ('Panama', 'Jiovany Ramos', 57667, 'DF', 'fully_verified'),
  ('Panama', 'Roderick Miller', 81659, 'DF', 'fully_verified'),
  ('Panama', 'Anibal Godoy', 2977, 'MF', 'fully_verified'),
  ('Panama', 'Adalberto Carrasquilla', 57807, 'MF', 'fully_verified'),
  ('Panama', 'Carlos Harvey', 71230, 'MF', 'fully_verified'),
  ('Panama', 'Cristian Martinez', 554208, 'MF', 'fully_verified'),
  ('Panama', 'Jose Luis Rodriguez', -68, 'MF', 'placeholder_lineup_pending'),
  ('Panama', 'Cesar Yanis', 57875, 'MF', 'fully_verified'),
  ('Panama', 'Yoel Barcenas', 46855, 'MF', 'fully_verified'),
  ('Panama', 'Alberto Quintero', 2978, 'MF', 'fully_verified'),
  ('Panama', 'Azarias Londono', 292396, 'MF', 'squad_missing_name_ok'),
  ('Panama', 'Ismael Diaz', 96615, 'FW', 'fully_verified'),
  ('Panama', 'Cecilio Waterman', 51648, 'FW', 'fully_verified'),
  ('Panama', 'Jose Fajardo', 2983, 'FW', 'fully_verified'),
  ('Panama', 'Tomas Rodriguez', 2979, 'FW', 'fully_verified');

-- Step 1: UPDATE rows matched by api_player_id (renames, reactivations, meta refresh)
UPDATE public.top_scorer_candidates tsc
SET
  name = i.name,
  team_name = i.team_name,
  position = COALESCE(i.position, tsc.position),
  id_verification = COALESCE(i.id_verification, tsc.id_verification),
  is_active = true
FROM _incoming_squad i
WHERE tsc.api_player_id = i.api_player_id;

-- Step 2: INSERT new rows (api_player_ids not in DB)
INSERT INTO public.top_scorer_candidates (team_name, name, api_player_id, position, id_verification, is_active)
SELECT i.team_name, i.name, i.api_player_id, i.position, i.id_verification, true
FROM _incoming_squad i
LEFT JOIN public.top_scorer_candidates tsc ON tsc.api_player_id = i.api_player_id
WHERE tsc.api_player_id IS NULL;

-- Step 3: DEACTIVATE active rows whose api_player_id is no longer in JSON
UPDATE public.top_scorer_candidates
SET is_active = false
WHERE is_active = true
  AND api_player_id NOT IN (SELECT api_player_id FROM _incoming_squad);

-- Step 4: Backfill flag_code from teams (any active row without flag)
UPDATE public.top_scorer_candidates tsc
SET flag_code = t.flag_code
FROM public.teams t
WHERE tsc.team_name = t.name
  AND (tsc.flag_code IS NULL OR tsc.flag_code <> t.flag_code);

-- Verification (not enforced, for SELECT-after audit):
-- SELECT COUNT(*) FROM top_scorer_candidates WHERE is_active = true; -- expect 1278
-- SELECT team_name, COUNT(*) FROM top_scorer_candidates WHERE is_active GROUP BY team_name; -- 48 teams

